import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";

import { discoverAbsorbSources } from "../lib/absorb/discovery.mjs";
import { extractAbsorbCandidates } from "../lib/absorb/extraction.mjs";
import { buildAbsorbProposal } from "../lib/absorb/proposal.mjs";
import { resolveLayeredSpecWithMeta } from "../lib/merging.mjs";
import { validateSpec } from "../lib/validation.mjs";

const scriptPath = resolve("scripts/agent-jump-start.mjs");

function makeTempDir() {
  return mkdtempSync(join(tmpdir(), "agent-jump-start-absorb-"));
}

function cleanupTempDir(directoryPath) {
  rmSync(directoryPath, { recursive: true, force: true });
}

function runCli(args, options = {}) {
  return spawnSync(process.execPath, [scriptPath, ...args], {
    encoding: "utf8",
    cwd: options.cwd,
    env: options.env,
    input: options.input,
  });
}

function expectSuccess(result) {
  assert.equal(result.status, 0, `Expected success.\nSTDOUT:\n${result.stdout}\nSTDERR:\n${result.stderr}`);
}

function expectFailure(result) {
  assert.notEqual(result.status, 0, "Expected command to fail.");
}

function makeMinimalSpec(extra = {}) {
  return {
    schemaVersion: 1,
    project: { name: "AbsorbTest", summary: "Absorb test spec", components: [] },
    workspaceInstructions: {
      sections: [{ title: "General rules", rules: ["Keep changes small."] }],
      validation: ["npm test"],
    },
    reviewChecklist: {
      intro: "Checklist",
      failureThreshold: 1,
      items: [{ title: "Check" }],
    },
    ...extra,
  };
}

function writeSpec(tempDir, specObject, fileName = "spec.yaml") {
  const specPath = join(tempDir, fileName);
  writeFileSync(specPath, `${JSON.stringify(specObject, null, 2)}\n`, "utf8");
  return specPath;
}

test("discoverAbsorbSources classifies managed and unmanaged files from known targets", () => {
  const tempDir = makeTempDir();
  try {
    writeFileSync(join(tempDir, "CLAUDE.md"), "# legacy\n", "utf8");
    writeFileSync(join(tempDir, "AGENTS.md"), "> Generated by Agent Jump Start v1.15.0\n", "utf8");

    const discovered = discoverAbsorbSources(tempDir);
    const claude = discovered.find((entry) => entry.relativePath === "CLAUDE.md");
    const agents = discovered.find((entry) => entry.relativePath === "AGENTS.md");
    assert.equal(claude?.classification, "unmanaged");
    assert.equal(agents?.classification, "managed");
  } finally {
    cleanupTempDir(tempDir);
  }
});

test("extractAbsorbCandidates reads validation blocks and strips frontmatter", () => {
  const source = {
    relativePath: ".cursor/rules/style.mdc",
    absolutePath: "/tmp/style.mdc",
    toolOfOrigin: "cursor",
    scope: "path-specific",
    tier: 1,
    classification: "unmanaged",
    byteSize: 0,
    content: `---\napplyTo: "**/*.ts"\ndescription: test\n---\n## Validation\n\n\`\`\`bash\nnpm test\nnpm run lint\n\`\`\`\n\n## TypeScript rules\n- Use strict mode.\n`,
  };
  const [candidate] = extractAbsorbCandidates([source]);
  assert.match(candidate.extractorNotes.join("\n"), /Stripped frontmatter/);
  assert.equal(candidate.validation.length, 2);
  assert.ok(candidate.sections.length >= 1);
  assert.equal(candidate.overallConfidence, "high");
});

test("buildAbsorbProposal reports conflicts for multiple primary per area", () => {
  const tempDir = makeTempDir();
  try {
    const specPath = writeSpec(tempDir, makeMinimalSpec());
    const meta = resolveLayeredSpecWithMeta(specPath);
    const candidates = [
      {
        source: { relativePath: "CLAUDE.md" },
        sections: [{ title: "Rules", rules: [{ value: "Rule A", provenance: "detected", source: "CLAUDE.md" }] }],
        validation: [{ value: "npm test", provenance: "detected", source: "CLAUDE.md" }],
        extractorNotes: [],
      },
      {
        source: { relativePath: "AGENTS.md" },
        sections: [{ title: "Rules", rules: [{ value: "Rule B", provenance: "detected", source: "AGENTS.md" }] }],
        validation: [{ value: "npm run lint", provenance: "detected", source: "AGENTS.md" }],
        extractorNotes: [],
      },
    ];

    const proposal = buildAbsorbProposal(meta, candidates, [
      { path: "CLAUDE.md", choice: "primary" },
      { path: "AGENTS.md", choice: "primary" },
    ]);
    assert.ok(proposal.diagnostics.conflicts.some((entry) => entry.type === "multiple-primary"));
  } finally {
    cleanupTempDir(tempDir);
  }
});

test("absorb --dry-run writes a deterministic proposal artifact", () => {
  const tempDir = makeTempDir();
  try {
    const specPath = writeSpec(tempDir, makeMinimalSpec(), "canonical-spec.yaml");
    writeFileSync(join(tempDir, "CLAUDE.md"), "## Validation\n\n```bash\nnpm run lint\n```\n", "utf8");
    writeFileSync(join(tempDir, "AGENTS.md"), "## Rules\n- Prefer small PRs\n", "utf8");

    const outputPath = join(tempDir, "absorb-proposal.json");
    const result = runCli(["absorb", "--spec", specPath, "--target", tempDir, "--dry-run", "--output", outputPath]);
    expectSuccess(result);
    assert.ok(existsSync(outputPath), "proposal output must be written");

    const proposal = JSON.parse(readFileSync(outputPath, "utf8"));
    assert.equal(proposal.version, 1);
    assert.ok(Array.isArray(proposal.sources));
    assert.ok(Array.isArray(proposal.decisions));
    assert.ok(proposal.proposedPatch.workspaceInstructions.validation.length >= 1);
  } finally {
    cleanupTempDir(tempDir);
  }
});

test("absorb --apply --selection writes leaf spec and sync/check converge", () => {
  const tempDir = makeTempDir();
  try {
    const specPath = writeSpec(tempDir, makeMinimalSpec(), "canonical-spec.yaml");
    writeFileSync(join(tempDir, "CLAUDE.md"), "## Validation\n\n```bash\nnpm run lint\n```\n", "utf8");
    writeFileSync(join(tempDir, "AGENTS.md"), "## TypeScript rules\n- Keep strict mode enabled.\n", "utf8");

    const selectionPath = join(tempDir, "absorb-selection.json");
    writeFileSync(selectionPath, `${JSON.stringify({
      version: 1,
      decisions: [
        { path: "CLAUDE.md", choice: "primary" },
        { path: "AGENTS.md", choice: "merge", mergeInto: "CLAUDE.md" },
      ],
    }, null, 2)}\n`, "utf8");

    const applyResult = runCli([
      "absorb",
      "--spec", specPath,
      "--target", tempDir,
      "--apply",
      "--selection", selectionPath,
    ]);
    expectSuccess(applyResult);

    const merged = JSON.parse(readFileSync(specPath, "utf8"));
    validateSpec(merged, specPath);
    assert.match(readFileSync(specPath, "utf8"), /npm run lint/);

    expectSuccess(runCli(["sync", "--spec", specPath, "--target", tempDir, "--force"]));
    expectSuccess(runCli(["check", "--spec", specPath, "--target", tempDir]));
  } finally {
    cleanupTempDir(tempDir);
  }
});

test("absorb non-interactive without mode flags exits with code 2", () => {
  const tempDir = makeTempDir();
  try {
    const specPath = writeSpec(tempDir, makeMinimalSpec(), "canonical-spec.yaml");
    writeFileSync(join(tempDir, "CLAUDE.md"), "# legacy\n", "utf8");
    const result = runCli(["absorb", "--spec", specPath, "--target", tempDir]);
    assert.equal(result.status, 2);
    assert.match(result.stderr, /interactive terminal|--dry-run/);
  } finally {
    cleanupTempDir(tempDir);
  }
});

test("absorb writes only the layered leaf spec file", () => {
  const tempDir = makeTempDir();
  try {
    const basePath = writeSpec(tempDir, makeMinimalSpec(), "base.yaml");
    const leafPath = join(tempDir, "leaf.yaml");
    writeFileSync(leafPath, `${JSON.stringify({
      extends: "./base.yaml",
      workspaceInstructions: {
        sections: [{ title: "Leaf rules", rules: ["Leaf only rule."] }],
      },
    }, null, 2)}\n`, "utf8");

    const baseBefore = readFileSync(basePath, "utf8");
    writeFileSync(join(tempDir, "CLAUDE.md"), "## Validation\n\n```bash\nnpm run lint\n```\n", "utf8");

    const selectionPath = join(tempDir, "selection.json");
    writeFileSync(selectionPath, `${JSON.stringify({
      version: 1,
      decisions: [{ path: "CLAUDE.md", choice: "primary" }],
    }, null, 2)}\n`, "utf8");

    expectSuccess(runCli(["absorb", "--spec", leafPath, "--target", tempDir, "--apply", "--selection", selectionPath]));
    assert.equal(readFileSync(basePath, "utf8"), baseBefore, "base layer must remain unchanged");
    assert.match(readFileSync(leafPath, "utf8"), /"extends": "\.\/base\.yaml"/, "leaf must preserve extends");
    assert.match(readFileSync(leafPath, "utf8"), /npm run lint/);
  } finally {
    cleanupTempDir(tempDir);
  }
});

test("init and sync refusal output contains absorb bridge tip", () => {
  const tempDir = makeTempDir();
  try {
    writeFileSync(join(tempDir, "CLAUDE.md"), "SENTINEL\n", "utf8");
    const initResult = runCli(["init", "--target", tempDir, "--non-interactive"]);
    expectFailure(initResult);
    assert.match(initResult.stdout + initResult.stderr, /agent-jump-start absorb/);

    const specPath = writeSpec(tempDir, makeMinimalSpec(), "spec.yaml");
    const syncResult = runCli(["sync", "--spec", specPath, "--target", tempDir]);
    expectFailure(syncResult);
    assert.match(syncResult.stdout + syncResult.stderr, /agent-jump-start absorb/);
  } finally {
    cleanupTempDir(tempDir);
  }
});

test("absorb dry-run is idempotent after sync --force manages all targets", () => {
  const tempDir = makeTempDir();
  try {
    const specPath = writeSpec(tempDir, makeMinimalSpec(), "spec.yaml");
    writeFileSync(join(tempDir, "CLAUDE.md"), "## Validation\n\n```bash\nnpm run lint\n```\n", "utf8");

    const selectionPath = join(tempDir, "selection.json");
    writeFileSync(selectionPath, `${JSON.stringify({
      version: 1,
      decisions: [{ path: "CLAUDE.md", choice: "primary" }],
    }, null, 2)}\n`, "utf8");
    expectSuccess(runCli(["absorb", "--spec", specPath, "--target", tempDir, "--apply", "--selection", selectionPath]));
    expectSuccess(runCli(["sync", "--spec", specPath, "--target", tempDir, "--force"]));

    const result = runCli(["absorb", "--spec", specPath, "--target", tempDir, "--dry-run"]);
    expectSuccess(result);
    assert.match(result.stdout + result.stderr, /Nothing to absorb/);
  } finally {
    cleanupTempDir(tempDir);
  }
});
