// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// P0-0 regression: re-importing an Agent Jump Start generated SKILL.md must
// be rejected consistently across validate-skill, import-skill, add-skill,
// and intake --import. A generated artifact that round-trips through the
// import pipeline corrupts the canonical spec with synthetic
// `Rule Categories by Priority` / `Quick Reference` / `Detailed Guidance`
// buckets and recursive `rcbp-*` / `qr-*` / `dg-*` rule ids.
//
// The scenarios covered here are the exact flows called out in the
// P0-0 roadmap section:
//
//   raw skill        → import       → render            (baseline, must still work)
//   rendered skill   → re-import                        (must be rejected)
//   legacy rendered  → re-import                        (must be rejected)
//   rendered with references/scripts/assets → re-import (must be rejected)

import assert from "node:assert/strict";
import test from "node:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";

const scriptPath = resolve("scripts/agent-jump-start.mjs");

function makeTempDir() {
  return mkdtempSync(join(tmpdir(), "agent-jump-start-p0-0-"));
}

function cleanup(path) {
  rmSync(path, { recursive: true, force: true });
}

function runCli(args, options = {}) {
  return spawnSync(process.execPath, [scriptPath, ...args], { encoding: "utf8", ...options });
}

function writeFile(filePath, content) {
  mkdirSync(resolve(filePath, ".."), { recursive: true });
  writeFileSync(filePath, content, "utf8");
}

function writeMinimalSpec(specPath) {
  writeFile(specPath, JSON.stringify({
    schemaVersion: 1,
    project: { name: "demo", summary: "demo" },
    workspaceInstructions: {
      packageManagerRule: "use existing",
      runtimeRule: "keep runtimes aligned",
      sections: [{ title: "General", rules: ["Keep changes small."] }],
    },
    skills: [],
  }));
}

const RAW_SKILL_MD = `---
name: demo-skill
description: A raw skill fixture that round-trips through the import pipeline.
---

# Demo Skill

## Best Practices

- Keep tests deterministic and independent of network access.
`;

// A SKILL.md that carries the Agent Jump Start provenance marker in the
// frontmatter metadata block. This is the shape produced by the renderer
// for every managed skill.
const GENERATED_SKILL_MD_FROM_FRONTMATTER = `---
name: demo-skill
description: A skill whose frontmatter declares Agent Jump Start provenance.
license: MPL-2.0
metadata:
  title: Demo Skill
  version: 1.0.0
  author: Imported
  generated_by: Agent Jump Start v2.1.0
  generated_from: docs/agent-jump-start/canonical-spec.yaml
---

# Demo Skill

**Version 1.0.0**
Imported

## Best Practices

- Keep tests deterministic.
`;

// A SKILL.md whose frontmatter was operator-scrubbed but whose body still
// carries the blockquote notice emitted by renderers.mjs. The guard must
// trip on the body marker as well, otherwise a simple metadata edit would
// bypass the protection.
const GENERATED_SKILL_MD_FROM_BODY = `---
name: demo-skill
description: A skill with a scrubbed metadata block but a generated body notice.
---

# Demo Skill

> Generated by Agent Jump Start v2.0.0 from \`docs/agent-jump-start/canonical-spec.yaml\`.
> Update the canonical spec and rerun \`render\` instead of hand-editing this file.

## Best Practices

- Keep tests deterministic.
`;

// Legacy artifact: an earlier Agent Jump Start major version. The detector
// is version-agnostic so the guard must still fire.
const LEGACY_GENERATED_SKILL_MD = `---
name: legacy-skill
description: A SKILL.md rendered by an earlier Agent Jump Start major.
license: MPL-2.0
metadata:
  title: Legacy Skill
  version: 0.9.0
  author: Imported
  generated_by: Agent Jump Start v1.2.3
  generated_from: docs/agent-jump-start/canonical-spec.yaml
---

# Legacy Skill

## Best Practices

- Keep tests deterministic.
`;

test("baseline: raw skill -> import-skill -> render stays structurally sane", () => {
  const tempDir = makeTempDir();
  try {
    const skillDir = join(tempDir, "demo-skill");
    writeFile(join(skillDir, "SKILL.md"), RAW_SKILL_MD);

    const specPath = join(tempDir, "spec.json");
    writeMinimalSpec(specPath);

    const importResult = runCli(["import-skill", "--spec", specPath, "--skill", skillDir]);
    assert.equal(
      importResult.status,
      0,
      `import-skill must accept a raw SKILL.md.\nSTDOUT:\n${importResult.stdout}\nSTDERR:\n${importResult.stderr}`,
    );

    const spec = JSON.parse(readFileSync(specPath, "utf8"));
    assert.equal(spec.skills.length, 1);
    assert.equal(spec.skills[0].slug, "demo-skill");
    // The import must not synthesize the collapse-pattern categories that
    // appear only when a generated SKILL.md is fed back into the importer.
    const categoryNames = spec.skills[0].categories.map((c) => c.name);
    assert.ok(
      !categoryNames.includes("Rule Categories by Priority"),
      `Raw import leaked a synthetic category. Got: ${categoryNames.join(", ")}`,
    );
    assert.ok(
      !spec.skills[0].rules.some((r) => /^rcbp-|^qr-|^dg-/.test(r.id)),
      "Raw import produced recursive rule ids; the corruption pattern must only appear on re-import.",
    );

    const renderResult = runCli(["render", "--spec", specPath, "--target", tempDir]);
    assert.equal(
      renderResult.status,
      0,
      `render must succeed on a raw import.\nSTDOUT:\n${renderResult.stdout}\nSTDERR:\n${renderResult.stderr}`,
    );
    assert.ok(existsSync(join(tempDir, ".claude", "skills", "demo-skill", "SKILL.md")));
  } finally {
    cleanup(tempDir);
  }
});

test("validate-skill rejects a generated SKILL.md detected via frontmatter metadata", () => {
  const tempDir = makeTempDir();
  try {
    const skillDir = join(tempDir, "demo-skill");
    writeFile(join(skillDir, "SKILL.md"), GENERATED_SKILL_MD_FROM_FRONTMATTER);

    const result = runCli(["validate-skill", skillDir]);
    assert.notEqual(result.status, 0, "validate-skill must reject a generated artifact");
    assert.match(result.stderr, /Agent Jump Start generated artifact/);
    assert.match(result.stderr, /v2\.1\.0/);
    assert.match(result.stderr, /canonical-spec\.yaml/);
    assert.match(result.stderr, /Import the raw upstream skill instead/);
  } finally {
    cleanup(tempDir);
  }
});

test("validate-skill rejects a generated SKILL.md detected via body blockquote", () => {
  const tempDir = makeTempDir();
  try {
    const skillDir = join(tempDir, "demo-skill");
    writeFile(join(skillDir, "SKILL.md"), GENERATED_SKILL_MD_FROM_BODY);

    const result = runCli(["validate-skill", skillDir]);
    assert.notEqual(result.status, 0, "validate-skill must trip on the body marker too");
    assert.match(result.stderr, /Agent Jump Start generated artifact/);
    assert.match(result.stderr, /v2\.0\.0/);
  } finally {
    cleanup(tempDir);
  }
});

test("validate-skill rejects a legacy generated SKILL.md (earlier AJS major)", () => {
  const tempDir = makeTempDir();
  try {
    const skillDir = join(tempDir, "legacy-skill");
    writeFile(join(skillDir, "SKILL.md"), LEGACY_GENERATED_SKILL_MD);

    const result = runCli(["validate-skill", skillDir]);
    assert.notEqual(result.status, 0, "the detector must be version-agnostic");
    assert.match(result.stderr, /Agent Jump Start generated artifact/);
    assert.match(result.stderr, /v1\.2\.3/);
  } finally {
    cleanup(tempDir);
  }
});

test("import-skill refuses a generated directory and leaves the spec untouched", () => {
  const tempDir = makeTempDir();
  try {
    const skillDir = join(tempDir, "demo-skill");
    writeFile(join(skillDir, "SKILL.md"), GENERATED_SKILL_MD_FROM_FRONTMATTER);

    const specPath = join(tempDir, "spec.json");
    writeMinimalSpec(specPath);
    const specBefore = readFileSync(specPath, "utf8");

    const result = runCli(["import-skill", "--spec", specPath, "--skill", skillDir]);
    assert.notEqual(result.status, 0, "import-skill must reject a generated artifact");
    assert.match(result.stderr, /Refusing to import/);
    assert.match(result.stderr, /Agent Jump Start v2\.1\.0/);
    assert.match(result.stderr, /corrupt the spec with synthetic `rcbp-\*` \/ `qr-\*` \/ `dg-\*` ids/);

    const specAfter = readFileSync(specPath, "utf8");
    assert.equal(specAfter, specBefore, "spec must not be modified when import is refused");
  } finally {
    cleanup(tempDir);
  }
});

test("import-skill refuses a generated standalone SKILL.md file and leaves the spec untouched", () => {
  const tempDir = makeTempDir();
  try {
    const skillMdPath = join(tempDir, "standalone.md");
    writeFile(skillMdPath, GENERATED_SKILL_MD_FROM_BODY);

    const specPath = join(tempDir, "spec.json");
    writeMinimalSpec(specPath);
    const specBefore = readFileSync(specPath, "utf8");

    const result = runCli(["import-skill", "--spec", specPath, "--skill", skillMdPath]);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /Refusing to import/);

    assert.equal(readFileSync(specPath, "utf8"), specBefore);
  } finally {
    cleanup(tempDir);
  }
});

test("add-skill refuses a generated local directory", () => {
  const tempDir = makeTempDir();
  try {
    const skillDir = join(tempDir, "demo-skill");
    writeFile(join(skillDir, "SKILL.md"), GENERATED_SKILL_MD_FROM_FRONTMATTER);

    const specPath = join(tempDir, "spec.json");
    writeMinimalSpec(specPath);
    const specBefore = readFileSync(specPath, "utf8");

    const result = runCli(["add-skill", skillDir, "--spec", specPath]);
    assert.notEqual(result.status, 0, "add-skill must inherit the import guard");
    assert.match(result.stderr, /Refusing to import/);

    assert.equal(readFileSync(specPath, "utf8"), specBefore);
  } finally {
    cleanup(tempDir);
  }
});

test("intake --import classifies a generated SKILL.md as invalid and refuses to import it", () => {
  const tempDir = makeTempDir();
  try {
    const skillDir = join(tempDir, ".claude", "skills", "demo-skill");
    writeFile(join(skillDir, "SKILL.md"), GENERATED_SKILL_MD_FROM_FRONTMATTER);

    const specPath = join(tempDir, "spec.json");
    writeMinimalSpec(specPath);
    const specBefore = readFileSync(specPath, "utf8");

    const result = runCli(["intake", "--spec", specPath, "--target", tempDir, "--import"]);
    // discoverUnmanagedSkills reports the artifact as invalid — the overall
    // exit code reflects invalid discoveries without --import, but with
    // --import the handler prints a report and exits cleanly because no
    // eligible skill was imported. Either way the spec must not be mutated.
    assert.match(result.stdout + result.stderr, /demo-skill/);
    assert.match(
      result.stdout + result.stderr,
      /Agent Jump Start|generated artifact|Re-importing generated/i,
      "intake must surface the generated-artifact diagnostic to the operator",
    );

    assert.equal(
      readFileSync(specPath, "utf8"),
      specBefore,
      "intake --import must not mutate the spec when the only discovery is a generated artifact",
    );
  } finally {
    cleanup(tempDir);
  }
});

test("rendered skill with references/scripts/assets is still refused on re-import", () => {
  const tempDir = makeTempDir();
  try {
    const skillDir = join(tempDir, "demo-skill");
    writeFile(join(skillDir, "SKILL.md"), GENERATED_SKILL_MD_FROM_FRONTMATTER);
    writeFile(join(skillDir, "references", "async-patterns.md"), "# Async patterns\n\nBody.\n");
    writeFile(join(skillDir, "scripts", "run.sh"), "#!/bin/sh\necho hi\n");
    writeFile(join(skillDir, "assets", "logo.txt"), "placeholder\n");

    const specPath = join(tempDir, "spec.json");
    writeMinimalSpec(specPath);
    const specBefore = readFileSync(specPath, "utf8");

    const result = runCli(["import-skill", "--spec", specPath, "--skill", skillDir]);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /Refusing to import/);
    assert.equal(
      readFileSync(specPath, "utf8"),
      specBefore,
      "bundled references/scripts/assets must not bypass the guard",
    );
  } finally {
    cleanup(tempDir);
  }
});

test("true round-trip: raw → import → render → re-import is refused", () => {
  const tempDir = makeTempDir();
  try {
    // Step 1: raw skill on disk
    const rawDir = join(tempDir, "raw", "demo-skill");
    writeFile(join(rawDir, "SKILL.md"), RAW_SKILL_MD);

    // Step 2: import into a canonical spec
    const specPath = join(tempDir, "spec.json");
    writeMinimalSpec(specPath);
    const importResult = runCli(["import-skill", "--spec", specPath, "--skill", rawDir]);
    assert.equal(importResult.status, 0, `raw import must succeed.\n${importResult.stderr}`);

    // Step 3: render the spec — this produces a generated SKILL.md mirror
    const renderRoot = join(tempDir, "workspace");
    mkdirSync(renderRoot, { recursive: true });
    const renderResult = runCli(["render", "--spec", specPath, "--target", renderRoot]);
    assert.equal(renderResult.status, 0, `render must succeed.\n${renderResult.stderr}`);

    const generatedSkillDir = join(renderRoot, ".claude", "skills", "demo-skill");
    const generatedSkillMd = join(generatedSkillDir, "SKILL.md");
    assert.ok(existsSync(generatedSkillMd), "render must produce the .claude/skills mirror");

    // Sanity: the rendered SKILL.md really is detectable as generated —
    // otherwise the rest of this test would be meaningless.
    const generatedContent = readFileSync(generatedSkillMd, "utf8");
    assert.match(
      generatedContent,
      /generated_by:\s*Agent Jump Start v|Generated by Agent Jump Start v/,
      "render must embed an Agent Jump Start provenance marker in the mirror",
    );

    // Step 4: try to re-import the rendered mirror into a fresh spec.
    const freshSpecPath = join(tempDir, "fresh-spec.json");
    writeMinimalSpec(freshSpecPath);
    const freshBefore = readFileSync(freshSpecPath, "utf8");

    const reimportResult = runCli([
      "import-skill",
      "--spec", freshSpecPath,
      "--skill", generatedSkillDir,
    ]);
    assert.notEqual(reimportResult.status, 0, "re-importing the rendered mirror must be refused");
    assert.match(reimportResult.stderr, /Refusing to import/);
    assert.match(reimportResult.stderr, /Agent Jump Start/);
    assert.equal(
      readFileSync(freshSpecPath, "utf8"),
      freshBefore,
      "fresh spec must remain untouched when re-import is refused",
    );
  } finally {
    cleanup(tempDir);
  }
});

test("inspectSkillSource surfaces the generated-artifact status with provenance details", async () => {
  const tempDir = makeTempDir();
  try {
    const { inspectSkillSource } = await import("../lib/intake.mjs");

    const fromFm = join(tempDir, "from-fm");
    writeFile(join(fromFm, "SKILL.md"), GENERATED_SKILL_MD_FROM_FRONTMATTER);
    const inspectedFm = inspectSkillSource(fromFm);
    assert.equal(inspectedFm.status, "generated-artifact");
    assert.equal(inspectedFm.provenance.source, "frontmatter");
    assert.equal(inspectedFm.provenance.version, "2.1.0");
    assert.equal(inspectedFm.provenance.generatedFrom, "docs/agent-jump-start/canonical-spec.yaml");

    const fromBody = join(tempDir, "from-body");
    writeFile(join(fromBody, "SKILL.md"), GENERATED_SKILL_MD_FROM_BODY);
    const inspectedBody = inspectSkillSource(fromBody);
    assert.equal(inspectedBody.status, "generated-artifact");
    assert.equal(inspectedBody.provenance.source, "body");
    assert.equal(inspectedBody.provenance.version, "2.0.0");

    const standalone = join(tempDir, "standalone.md");
    writeFile(standalone, GENERATED_SKILL_MD_FROM_FRONTMATTER);
    const inspectedStandalone = inspectSkillSource(standalone);
    assert.equal(inspectedStandalone.status, "generated-artifact");
    assert.equal(inspectedStandalone.provenance.version, "2.1.0");
  } finally {
    cleanup(tempDir);
  }
});
