// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import { copyFileSync, existsSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { ensureDirectory } from "./utils.mjs";

const GENERATED_MANIFEST_PATH = "docs/agent-jump-start/generated-manifest.json";

// ---------------------------------------------------------------------------
// Provenance classification
//
// A file on disk is considered tool-managed only when it contains one of the
// structured provenance signatures that lib/renderers.mjs actually emits:
//
//   - Markdown/MDC:  "Generated by Agent Jump Start v<N>"  (inside a blockquote)
//   - YAML/MDC frontmatter:  "generated_by: Agent Jump Start v<N>"
//   - JSON manifest:  "\"generatedBy\": \"Agent Jump Start v<N>"
//
// Requiring the full signature (with a version digit) prevents false positives
// where an operator-authored file happens to mention "Agent Jump Start" in
// prose. Absence of every signature means the file predates the tool's
// ownership and must never be overwritten without an explicit operator
// decision.
// ---------------------------------------------------------------------------

const PROVENANCE_SIGNATURES = [
  /Generated by Agent Jump Start v\d/,
  /generated_by:\s*Agent Jump Start v\d/,
  /"generatedBy"\s*:\s*"Agent Jump Start v\d/,
];

export function hasProvenanceSignature(content) {
  return PROVENANCE_SIGNATURES.some((pattern) => pattern.test(content));
}

export function classifyExistingFile(absolutePath) {
  if (!existsSync(absolutePath)) return "absent";
  let stats;
  try {
    stats = statSync(absolutePath);
  } catch {
    return "unreadable";
  }
  // A non-file at a render target path is a filesystem collision, not an
  // operator-authored file. Surface it to the write path so the error
  // reporter can blame the filesystem layout rather than the overwrite guard.
  if (!stats.isFile()) return "not-a-file";
  try {
    const content = readFileSync(absolutePath, "utf8");
    return hasProvenanceSignature(content) ? "managed" : "unmanaged";
  } catch {
    return "unreadable";
  }
}

function readManagedPathsFromManifest(targetRoot) {
  const manifestPath = join(resolve(targetRoot), GENERATED_MANIFEST_PATH);
  if (!existsSync(manifestPath)) {
    return new Set();
  }

  try {
    const content = readFileSync(manifestPath, "utf8");
    if (!hasProvenanceSignature(content)) {
      return new Set();
    }

    const manifest = JSON.parse(content);
    const managedPaths = Array.isArray(manifest.files)
      ? manifest.files.filter((value) => typeof value === "string")
      : [];
    return new Set(managedPaths);
  } catch {
    return new Set();
  }
}

function classifyGeneratedPath(absolutePath, relativePath, manifestManagedPaths) {
  const kind = classifyExistingFile(absolutePath);
  if (kind === "unmanaged" && manifestManagedPaths.has(relativePath)) {
    return "managed";
  }
  return kind;
}

export function classifyPreWriteCollisions(generatedFiles, targetRoot) {
  const targetAbs = resolve(targetRoot);
  const manifestManagedPaths = readManagedPathsFromManifest(targetRoot);
  const absent = [];
  const managed = [];
  const unmanaged = [];
  const unreadable = [];
  for (const relativePath of Object.keys(generatedFiles)) {
    const kind = classifyGeneratedPath(join(targetAbs, relativePath), relativePath, manifestManagedPaths);
    if (kind === "absent" || kind === "not-a-file") absent.push(relativePath);
    else if (kind === "managed") managed.push(relativePath);
    else if (kind === "unmanaged") unmanaged.push(relativePath);
    else unreadable.push(relativePath);
  }
  return { absent, managed, unmanaged, unreadable };
}

function backupTimestamp() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

export function backupPathFor(absolutePath, stamp = backupTimestamp()) {
  return `${absolutePath}.ajs-backup-${stamp}`;
}

function makeGeneratedFileFailure(relativePath, cause, detail, nextStep) {
  return {
    relativePath,
    cause,
    detail,
    nextStep,
  };
}

export function formatGeneratedFileFailure(failure) {
  const lines = [`FAIL ${failure.relativePath}`];
  if (failure.cause) {
    lines.push(`  Cause: ${failure.cause}`);
  }
  if (failure.detail) {
    lines.push(`  Detail: ${failure.detail}`);
  }
  if (failure.nextStep) {
    lines.push(`  Next step: ${failure.nextStep}`);
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Write / check / clean generated files
// ---------------------------------------------------------------------------

export function writeGeneratedFiles(generatedFiles, targetRoot) {
  for (const [relativePath, content] of Object.entries(generatedFiles)) {
    const absolutePath = join(resolve(targetRoot), relativePath);
    ensureDirectory(absolutePath);
    writeFileSync(absolutePath, content, "utf8");
  }
}

// ---------------------------------------------------------------------------
// Safe write with per-path decisions
//
// Decisions are keyed by relative path. Supported values:
//   - "overwrite"             — write unconditionally (default for absent & managed)
//   - "keep"                  — skip this path entirely (operator keeps existing file)
//   - "backup-then-overwrite" — copy existing file to a timestamped sibling, then write
//
// Paths that are absent on disk are always written. Paths classified as
// managed are overwritten unless the decision map explicitly says otherwise.
// Paths classified as unmanaged require a decision from the caller; if none
// is provided this function throws, which is the last line of defense
// against silent clobbering.
// ---------------------------------------------------------------------------

export function applyWriteDecisions(generatedFiles, targetRoot, { decisions = {}, stamp } = {}) {
  const targetAbs = resolve(targetRoot);
  const manifestManagedPaths = readManagedPathsFromManifest(targetRoot);
  const written = [];
  const kept = [];
  const backedUp = [];
  const backupStamp = stamp ?? backupTimestamp();

  for (const [relativePath, content] of Object.entries(generatedFiles)) {
    const absolutePath = join(targetAbs, relativePath);
    const existed = existsSync(absolutePath);
    const kind = classifyGeneratedPath(absolutePath, relativePath, manifestManagedPaths);
    const decision = decisions[relativePath]
      ?? (kind === "unmanaged" ? null : "overwrite");

    if (decision === null) {
      throw new Error(
        `Refusing to overwrite unmanaged pre-existing file without a decision: ${relativePath}`,
      );
    }

    if (decision === "keep") {
      kept.push(relativePath);
      continue;
    }

    if (decision === "backup-then-overwrite" && existed) {
      const backupAbs = backupPathFor(absolutePath, backupStamp);
      copyFileSync(absolutePath, backupAbs);
      backedUp.push({ relativePath, backupPath: backupAbs });
    }

    ensureDirectory(absolutePath);
    writeFileSync(absolutePath, content, "utf8");
    written.push(relativePath);
  }

  return { written, kept, backedUp };
}

export function checkGeneratedFiles(generatedFiles, targetRoot) {
  const targetAbsolutePath = resolve(targetRoot);
  const failures = [];
  const passes = [];
  let manifestContentMismatch = false;

  for (const [relativePath, expectedContent] of Object.entries(generatedFiles)) {
    const absolutePath = join(targetAbsolutePath, relativePath);
    if (!existsSync(absolutePath)) {
      failures.push(makeGeneratedFileFailure(
        relativePath,
        "Generated file is missing from disk.",
        "The file was deleted, moved, or skipped by a failed write.",
        "Run sync to regenerate it.",
      ));
      continue;
    }

    const actualContent = readFileSync(absolutePath, "utf8");
    if (actualContent !== expectedContent) {
      if (relativePath === GENERATED_MANIFEST_PATH) {
        manifestContentMismatch = true;
        continue;
      }
      failures.push(makeGeneratedFileFailure(
        relativePath,
        "Generated content no longer matches the current canonical spec.",
        "The file was likely edited by hand or left behind from an older render.",
        "Run sync to rewrite it. If the drift comes back, move the intended change into the spec instead of editing generated files.",
      ));
      continue;
    }

    passes.push(`OK ${relativePath}`);
  }

  const manifestPath = join(targetAbsolutePath, GENERATED_MANIFEST_PATH);
  if (existsSync(manifestPath)) {
    const manifestContent = readFileSync(manifestPath, "utf8");
    try {
      const manifest = JSON.parse(manifestContent);
      const expectedPaths = new Set(Object.keys(generatedFiles));
      for (const relativePath of manifest.files ?? []) {
        if (!expectedPaths.has(relativePath) && existsSync(join(targetAbsolutePath, relativePath))) {
          failures.push(makeGeneratedFileFailure(
            relativePath,
            "A previously generated file still exists, but the current spec no longer owns it.",
            "A prior render left an obsolete managed output behind.",
            "Run sync with write access so the stale file can be removed. If it still remains, delete the file manually and rerun sync.",
          ));
        }
      }
    } catch (error) {
      failures.push(makeGeneratedFileFailure(
        GENERATED_MANIFEST_PATH,
        "The generated manifest cannot be read safely.",
        error instanceof Error ? error.message : String(error),
        "Run sync to rewrite the manifest. If stale outputs still remain afterward, delete the manifest and rerun sync.",
      ));
      return { failures, passes };
    }
  }

  if (manifestContentMismatch) {
    failures.push(makeGeneratedFileFailure(
      GENERATED_MANIFEST_PATH,
      "Generated content no longer matches the current canonical spec.",
      "The manifest was likely edited by hand or left behind from an older render.",
      "Run sync to rewrite it. If the drift comes back, stop editing generated files directly and update the spec instead.",
    ));
  }

  return { failures, passes };
}

export function cleanStaleFiles(generatedFiles, targetRoot) {
  const targetAbsolutePath = resolve(targetRoot);
  const manifestPath = join(targetAbsolutePath, "docs/agent-jump-start/generated-manifest.json");
  const removed = [];

  if (!existsSync(manifestPath)) {
    return removed;
  }

  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const expectedPaths = new Set(Object.keys(generatedFiles));

  for (const relativePath of manifest.files ?? []) {
    if (!expectedPaths.has(relativePath)) {
      const absolutePath = join(targetAbsolutePath, relativePath);
      if (existsSync(absolutePath)) {
        rmSync(absolutePath, { force: true });
        removed.push(relativePath);

        // Remove empty parent directories up to target root
        let dir = dirname(absolutePath);
        while (dir !== targetAbsolutePath && dir.startsWith(targetAbsolutePath)) {
          try {
            const entries = readdirSync(dir);
            if (entries.length === 0) {
              rmSync(dir, { force: true });
              dir = dirname(dir);
            } else {
              break;
            }
          } catch {
            break;
          }
        }
      }
    }
  }

  return removed;
}

export function cleanDirectoryIfExists(directoryPath) {
  if (existsSync(directoryPath)) {
    rmSync(directoryPath, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// Discovery
// ---------------------------------------------------------------------------

export function discoverPackageRoot() {
  const scriptDir = dirname(new URL(import.meta.url).pathname);
  return resolve(scriptDir, "..");
}

export function listAvailableProfiles() {
  const packageRoot = discoverPackageRoot();
  const profileDir = join(packageRoot, "specs", "profiles");
  if (!existsSync(profileDir)) {
    return [];
  }
  return readdirSync(profileDir)
    .filter((f) => f.endsWith(".profile.yaml"))
    .map((f) => ({
      file: f,
      path: join(profileDir, f),
      name: f.replace(".profile.yaml", ""),
    }));
}

// ---------------------------------------------------------------------------
// Disabled-agent root cleanup
//
// After stale managed files are removed, disabled-agent cleanup targets may
// remain on disk. Targets come in two forms:
//   - Directories (path ends with "/"): removed if empty, reported if
//     non-empty with unmanaged content.
//   - Files (no trailing "/"): removed if AJS-managed (provenance marker),
//     reported if unmanaged (operator-authored).
// ---------------------------------------------------------------------------

/**
 * Clean disabled-agent targets and report residuals.
 *
 * @param {Set<string>|null} enabledAgents — the set of enabled agent IDs, or null for all
 * @param {string} targetRoot — absolute path to the workspace root
 * @param {Map} agentRegistry — the agent registry Map
 * @returns {{ removed: string[], residuals: { agentId: string, displayName: string, root: string }[] }}
 */
export function cleanDisabledAgentRoots(enabledAgents, targetRoot, agentRegistry) {
  const removed = [];
  const residuals = [];

  if (!enabledAgents) {
    return { removed, residuals };
  }

  for (const [agentId, entry] of agentRegistry) {
    if (enabledAgents.has(agentId)) continue;
    for (const target of entry.agentRoots ?? []) {
      const targetPath = join(resolve(targetRoot), target);
      if (!existsSync(targetPath)) continue;

      const isDirectoryTarget = target.endsWith("/");

      if (isDirectoryTarget) {
        try {
          if (!statSync(targetPath).isDirectory()) continue;
        } catch {
          continue;
        }

        const hasContent = directoryHasFiles(targetPath);
        if (!hasContent) {
          rmSync(targetPath, { recursive: true, force: true });
          removed.push(target);
        } else {
          residuals.push({ agentId, displayName: entry.displayName, root: target });
        }
      } else {
        // File target (e.g. GEMINI.md, CONVENTIONS.md, .windsurfrules, .roorules, .clinerules)
        try {
          if (!statSync(targetPath).isFile()) continue;
        } catch {
          continue;
        }

        const kind = classifyExistingFile(targetPath);
        if (kind === "managed") {
          rmSync(targetPath, { force: true });
          removed.push(target);
        } else {
          // Unmanaged operator-authored file — do not delete, report
          residuals.push({ agentId, displayName: entry.displayName, root: target });
        }
      }
    }
  }

  return { removed, residuals };
}

function directoryHasFiles(dirPath) {
  try {
    const entries = readdirSync(dirPath);
    for (const entry of entries) {
      const entryPath = join(dirPath, entry);
      try {
        const stats = statSync(entryPath);
        if (stats.isFile()) return true;
        if (stats.isDirectory() && directoryHasFiles(entryPath)) return true;
      } catch {
        continue;
      }
    }
  } catch {
    return false;
  }
  return false;
}

export function listManagedFiles(rootPath) {
  const entries = [];

  function walk(currentPath) {
    for (const entry of readdirSync(currentPath)) {
      const absolutePath = join(currentPath, entry);
      const relativePath = relative(rootPath, absolutePath);
      const stats = statSync(absolutePath);
      if (stats.isDirectory()) {
        walk(absolutePath);
        continue;
      }
      entries.push(relativePath);
    }
  }

  walk(rootPath);
  return entries.sort();
}
