// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import { copyFileSync, cpSync, existsSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { ensureDirectory } from "./utils.mjs";

const GENERATED_MANIFEST_PATH = "docs/agent-jump-start/generated-manifest.json";

// ---------------------------------------------------------------------------
// Provenance classification
//
// A file on disk is considered tool-managed only when it contains one of the
// structured provenance signatures that lib/renderers.mjs actually emits:
//
//   - Markdown/MDC:  "Generated by Agent Jump Start v<N>"  (inside a blockquote)
//   - YAML/MDC frontmatter:  "generated_by: Agent Jump Start v<N>"
//   - JSON manifest:  "\"generatedBy\": \"Agent Jump Start v<N>"
//
// Requiring the full signature (with a version digit) prevents false positives
// where an operator-authored file happens to mention "Agent Jump Start" in
// prose. Absence of every signature means the file predates the tool's
// ownership and must never be overwritten without an explicit operator
// decision.
// ---------------------------------------------------------------------------

const PROVENANCE_SIGNATURES = [
  /Generated by Agent Jump Start v\d/,
  /generated_by:\s*Agent Jump Start v\d/,
  /"generatedBy"\s*:\s*"Agent Jump Start v\d/,
];

export function hasProvenanceSignature(content) {
  return PROVENANCE_SIGNATURES.some((pattern) => pattern.test(content));
}

export function classifyExistingFile(absolutePath) {
  if (!existsSync(absolutePath)) return "absent";
  let stats;
  try {
    stats = statSync(absolutePath);
  } catch {
    return "unreadable";
  }
  // A non-file at a render target path is a filesystem collision, not an
  // operator-authored file. Surface it to the write path so the error
  // reporter can blame the filesystem layout rather than the overwrite guard.
  if (!stats.isFile()) return "not-a-file";
  try {
    const content = readFileSync(absolutePath, "utf8");
    return hasProvenanceSignature(content) ? "managed" : "unmanaged";
  } catch {
    return "unreadable";
  }
}

export function readManagedPathsFromManifest(targetRoot) {
  const manifestPath = join(resolve(targetRoot), GENERATED_MANIFEST_PATH);
  if (!existsSync(manifestPath)) {
    return new Set();
  }

  try {
    const content = readFileSync(manifestPath, "utf8");
    if (!hasProvenanceSignature(content)) {
      return new Set();
    }

    const manifest = JSON.parse(content);
    const managedPaths = Array.isArray(manifest.files)
      ? manifest.files.filter((value) => typeof value === "string")
      : [];
    return new Set(managedPaths);
  } catch {
    return new Set();
  }
}

// ---------------------------------------------------------------------------
// Preserved-path state (P0-D sync/check convergence contract)
//
// `sync --keep-existing` records operator-preserved paths in the generated
// manifest under a `preserved` array so standalone `check` can distinguish
// intentional non-convergence from ordinary drift. Entries survive across
// sync runs that do not touch those paths; they are pruned automatically
// when the file is overwritten/backed up, absorbed into the spec, or when
// its on-disk state no longer matches the preserved contract (file missing
// or now carries the provenance marker).
// ---------------------------------------------------------------------------

export function readManifestPreservedEntries(targetRoot) {
  const manifestPath = join(resolve(targetRoot), GENERATED_MANIFEST_PATH);
  const entries = new Map();
  if (!existsSync(manifestPath)) return entries;
  try {
    const content = readFileSync(manifestPath, "utf8");
    if (!hasProvenanceSignature(content)) return entries;
    const manifest = JSON.parse(content);
    if (!Array.isArray(manifest.preserved)) return entries;
    for (const entry of manifest.preserved) {
      if (entry && typeof entry.path === "string") {
        entries.set(entry.path, {
          path: entry.path,
          preservedAt: typeof entry.preservedAt === "string" ? entry.preservedAt : null,
        });
      }
    }
  } catch { /* manifest unreadable — behave as if no preserved state */ }
  return entries;
}

export function readManifestPreservedPaths(targetRoot) {
  return new Set(readManifestPreservedEntries(targetRoot).keys());
}

function classifyGeneratedPath(absolutePath, relativePath, manifestManagedPaths) {
  const kind = classifyExistingFile(absolutePath);
  if (kind === "unmanaged" && manifestManagedPaths.has(relativePath)) {
    return "managed";
  }
  return kind;
}

export function classifyPreWriteCollisions(generatedFiles, targetRoot) {
  const targetAbs = resolve(targetRoot);
  const manifestManagedPaths = readManagedPathsFromManifest(targetRoot);
  const absent = [];
  const managed = [];
  const unmanaged = [];
  const unreadable = [];
  for (const relativePath of Object.keys(generatedFiles)) {
    const kind = classifyGeneratedPath(join(targetAbs, relativePath), relativePath, manifestManagedPaths);
    if (kind === "absent" || kind === "not-a-file") absent.push(relativePath);
    else if (kind === "managed") managed.push(relativePath);
    else if (kind === "unmanaged") unmanaged.push(relativePath);
    else unreadable.push(relativePath);
  }
  return { absent, managed, unmanaged, unreadable };
}

function backupTimestamp() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

export function backupPathFor(absolutePath, stamp = backupTimestamp()) {
  return `${absolutePath}.ajs-backup-${stamp}`;
}

function makeGeneratedFileFailure(relativePath, cause, detail, nextStep) {
  return {
    relativePath,
    cause,
    detail,
    nextStep,
  };
}

export function formatGeneratedFileFailure(failure) {
  const lines = [`FAIL ${failure.relativePath}`];
  if (failure.cause) {
    lines.push(`  Cause: ${failure.cause}`);
  }
  if (failure.detail) {
    lines.push(`  Detail: ${failure.detail}`);
  }
  if (failure.nextStep) {
    lines.push(`  Next step: ${failure.nextStep}`);
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Write / check / clean generated files
// ---------------------------------------------------------------------------

export function writeGeneratedFiles(generatedFiles, targetRoot) {
  for (const [relativePath, content] of Object.entries(generatedFiles)) {
    const absolutePath = join(resolve(targetRoot), relativePath);
    ensureDirectory(absolutePath);
    writeFileSync(absolutePath, content, "utf8");
  }
}

// ---------------------------------------------------------------------------
// Safe write with per-path decisions
//
// Decisions are keyed by relative path. Supported values:
//   - "overwrite"             — write unconditionally (default for absent & managed)
//   - "keep"                  — skip this path entirely (operator keeps existing file)
//   - "backup-then-overwrite" — copy existing file to a timestamped sibling, then write
//
// Paths that are absent on disk are always written. Paths classified as
// managed are overwritten unless the decision map explicitly says otherwise.
// Paths classified as unmanaged require a decision from the caller; if none
// is provided this function throws, which is the last line of defense
// against silent clobbering.
// ---------------------------------------------------------------------------

export function applyWriteDecisions(generatedFiles, targetRoot, { decisions = {}, stamp } = {}) {
  const targetAbs = resolve(targetRoot);
  const manifestManagedPaths = readManagedPathsFromManifest(targetRoot);
  const written = [];
  const kept = [];
  const backedUp = [];
  const backupStamp = stamp ?? backupTimestamp();

  for (const [relativePath, content] of Object.entries(generatedFiles)) {
    const absolutePath = join(targetAbs, relativePath);
    const existed = existsSync(absolutePath);
    const kind = classifyGeneratedPath(absolutePath, relativePath, manifestManagedPaths);
    const decision = decisions[relativePath]
      ?? (kind === "unmanaged" ? null : "overwrite");

    if (decision === null) {
      throw new Error(
        `Refusing to overwrite unmanaged pre-existing file without a decision: ${relativePath}`,
      );
    }

    if (decision === "keep") {
      kept.push(relativePath);
      continue;
    }

    if (decision === "backup-then-overwrite" && existed) {
      const backupAbs = backupPathFor(absolutePath, backupStamp);
      copyFileSync(absolutePath, backupAbs);
      backedUp.push({ relativePath, backupPath: backupAbs });
    }

    ensureDirectory(absolutePath);
    writeFileSync(absolutePath, content, "utf8");
    written.push(relativePath);
  }

  return { written, kept, backedUp };
}

export function checkGeneratedFiles(generatedFiles, targetRoot) {
  const targetAbsolutePath = resolve(targetRoot);
  const failures = [];
  const passes = [];
  const preserved = [];
  let manifestContentMismatch = false;
  const preservedEntries = readManifestPreservedEntries(targetRoot);

  for (const [relativePath, expectedContent] of Object.entries(generatedFiles)) {
    const absolutePath = join(targetAbsolutePath, relativePath);
    if (!existsSync(absolutePath)) {
      failures.push(makeGeneratedFileFailure(
        relativePath,
        "Generated file is missing from disk.",
        "The file was deleted, moved, or skipped by a failed write.",
        "Run sync to regenerate it.",
      ));
      continue;
    }

    const actualContent = readFileSync(absolutePath, "utf8");
    if (actualContent !== expectedContent) {
      if (relativePath === GENERATED_MANIFEST_PATH) {
        // The on-disk manifest may legitimately differ from a freshly rendered
        // one when a prior sync --keep-existing moved paths from files[] into
        // preserved[]. Treat that case as semantically equivalent: the union
        // files[] ∪ preserved[].path[] must still equal the expected files[],
        // and the identifying headers must match.
        if (!manifestsAreSemanticallyEquivalent(expectedContent, actualContent)) {
          manifestContentMismatch = true;
        }
        continue;
      }
      // Content drift: distinguish intentional operator preservation from
      // ordinary drift. A path qualifies as preserved only when a prior
      // sync --keep-existing recorded it in manifest.preserved AND the
      // on-disk file is still operator-authored (no provenance marker).
      // Anything else remains drift.
      if (preservedEntries.has(relativePath) && classifyExistingFile(absolutePath) === "unmanaged") {
        preserved.push({
          relativePath,
          preservedAt: preservedEntries.get(relativePath)?.preservedAt ?? null,
        });
        continue;
      }
      failures.push(makeGeneratedFileFailure(
        relativePath,
        "Generated content no longer matches the current canonical spec.",
        "The file was likely edited by hand or left behind from an older render.",
        "Run sync to rewrite it. If the drift comes back, move the intended change into the spec instead of editing generated files.",
      ));
      continue;
    }

    passes.push(`OK ${relativePath}`);
  }

  const manifestPath = join(targetAbsolutePath, GENERATED_MANIFEST_PATH);
  if (existsSync(manifestPath)) {
    const manifestContent = readFileSync(manifestPath, "utf8");
    try {
      const manifest = JSON.parse(manifestContent);
      const expectedPaths = new Set(Object.keys(generatedFiles));
      for (const relativePath of manifest.files ?? []) {
        if (!expectedPaths.has(relativePath) && existsSync(join(targetAbsolutePath, relativePath))) {
          failures.push(makeGeneratedFileFailure(
            relativePath,
            "A previously generated file still exists, but the current spec no longer owns it.",
            "A prior render left an obsolete managed output behind.",
            "Run sync with write access so the stale file can be removed. If it still remains, delete the file manually and rerun sync.",
          ));
        }
      }
    } catch (error) {
      failures.push(makeGeneratedFileFailure(
        GENERATED_MANIFEST_PATH,
        "The generated manifest cannot be read safely.",
        error instanceof Error ? error.message : String(error),
        "Run sync to rewrite the manifest. If stale outputs still remain afterward, delete the manifest and rerun sync.",
      ));
      return { failures, passes };
    }
  }

  if (manifestContentMismatch) {
    failures.push(makeGeneratedFileFailure(
      GENERATED_MANIFEST_PATH,
      "Generated content no longer matches the current canonical spec.",
      "The manifest was likely edited by hand or left behind from an older render.",
      "Run sync to rewrite it. If the drift comes back, stop editing generated files directly and update the spec instead.",
    ));
  }

  return { failures, passes, preserved };
}

function manifestsAreSemanticallyEquivalent(expectedContent, actualContent) {
  let expected;
  let actual;
  try {
    expected = JSON.parse(expectedContent);
    actual = JSON.parse(actualContent);
  } catch {
    return false;
  }
  if (expected.generatedBy !== actual.generatedBy) return false;
  if (expected.generatedFrom !== actual.generatedFrom) return false;
  if (expected.generatorVersion !== actual.generatorVersion) return false;
  if (JSON.stringify(expected.agents ?? null) !== JSON.stringify(actual.agents ?? null)) return false;

  const expectedFiles = new Set(Array.isArray(expected.files) ? expected.files : []);
  const actualFiles = new Set(Array.isArray(actual.files) ? actual.files : []);
  const preservedPaths = Array.isArray(actual.preserved)
    ? actual.preserved.map((entry) => entry?.path).filter((p) => typeof p === "string")
    : [];
  const actualUnion = new Set([...actualFiles, ...preservedPaths]);

  if (expectedFiles.size !== actualUnion.size) return false;
  for (const path of expectedFiles) {
    if (!actualUnion.has(path)) return false;
  }
  return true;
}

// ---------------------------------------------------------------------------
// Manifest preserved-state merge (shared write-path helper)
//
// Given a freshly rendered manifest JSON string and this run's kept/overwritten
// decisions, return a new JSON string where:
//   - files[] excludes paths currently in the preserved set
//   - preserved[] reflects: existing preserved entries, minus newlyOverwritten,
//     plus newlyKept (with fresh timestamp), filtered to entries whose on-disk
//     file still exists AND is still unmanaged (no provenance marker).
// Invalid input (malformed JSON, missing fields) falls back to the original
// content unchanged, mirroring the defensive behavior of the legacy
// rewriteManifestForKeptPaths helper it replaces.
// ---------------------------------------------------------------------------

export function mergeManifestPreservedState(manifestContent, targetRoot, { newlyKept = [], newlyOverwritten = [], stamp } = {}) {
  let manifest;
  try {
    manifest = JSON.parse(manifestContent);
  } catch {
    return manifestContent;
  }

  const existing = readManifestPreservedEntries(targetRoot);
  for (const path of newlyOverwritten) existing.delete(path);

  const timestamp = stamp ?? new Date().toISOString();
  for (const path of newlyKept) {
    existing.set(path, { path, preservedAt: timestamp });
  }

  const targetAbs = resolve(targetRoot);
  const validEntries = [];
  for (const entry of existing.values()) {
    const absolutePath = join(targetAbs, entry.path);
    if (classifyExistingFile(absolutePath) !== "unmanaged") continue;
    validEntries.push({
      path: entry.path,
      preservedAt: entry.preservedAt ?? timestamp,
    });
  }
  validEntries.sort((a, b) => a.path.localeCompare(b.path));

  const preservedPathSet = new Set(validEntries.map((entry) => entry.path));
  const filteredFiles = (Array.isArray(manifest.files) ? manifest.files : [])
    .filter((path) => !preservedPathSet.has(path));

  const nextManifest = { ...manifest, files: filteredFiles };
  if (validEntries.length > 0) {
    nextManifest.preserved = validEntries;
  } else {
    delete nextManifest.preserved;
  }
  return `${JSON.stringify(nextManifest, null, 2)}\n`;
}

export function cleanStaleFiles(generatedFiles, targetRoot) {
  const targetAbsolutePath = resolve(targetRoot);
  const manifestPath = join(targetAbsolutePath, "docs/agent-jump-start/generated-manifest.json");
  const removed = [];

  if (!existsSync(manifestPath)) {
    return removed;
  }

  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const expectedPaths = new Set(Object.keys(generatedFiles));

  for (const relativePath of manifest.files ?? []) {
    if (!expectedPaths.has(relativePath)) {
      const absolutePath = join(targetAbsolutePath, relativePath);
      if (existsSync(absolutePath)) {
        rmSync(absolutePath, { force: true });
        removed.push(relativePath);

        // Remove empty parent directories up to target root
        let dir = dirname(absolutePath);
        while (dir !== targetAbsolutePath && dir.startsWith(targetAbsolutePath)) {
          try {
            const entries = readdirSync(dir);
            if (entries.length === 0) {
              rmSync(dir, { force: true });
              dir = dirname(dir);
            } else {
              break;
            }
          } catch {
            break;
          }
        }
      }
    }
  }

  return removed;
}

function pruneEmptyParentDirectories(absolutePath, targetRoot) {
  const targetAbsolutePath = resolve(targetRoot);
  let dir = dirname(absolutePath);
  while (dir !== targetAbsolutePath && dir.startsWith(targetAbsolutePath)) {
    try {
      const entries = readdirSync(dir);
      if (entries.length === 0) {
        rmSync(dir, { force: true });
        dir = dirname(dir);
      } else {
        break;
      }
    } catch {
      break;
    }
  }
}

function backupExistingPath(absolutePath, stamp) {
  const stats = statSync(absolutePath);
  const backupAbs = backupPathFor(absolutePath, stamp);
  if (stats.isDirectory()) {
    cpSync(absolutePath, backupAbs, { recursive: true });
  } else {
    copyFileSync(absolutePath, backupAbs);
  }
  return backupAbs;
}

function removeTargetPath(absolutePath, relativePath, targetRoot, { backup = false, stamp } = {}) {
  const backupPath = backup ? backupExistingPath(absolutePath, stamp) : null;
  rmSync(absolutePath, { recursive: true, force: true });
  pruneEmptyParentDirectories(absolutePath, targetRoot);
  return backupPath;
}

export function cleanDirectoryIfExists(directoryPath) {
  if (existsSync(directoryPath)) {
    rmSync(directoryPath, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// Discovery
// ---------------------------------------------------------------------------

export function discoverPackageRoot() {
  const scriptDir = dirname(new URL(import.meta.url).pathname);
  return resolve(scriptDir, "..");
}

export function listAvailableProfiles() {
  const packageRoot = discoverPackageRoot();
  const profileDir = join(packageRoot, "specs", "profiles");
  if (!existsSync(profileDir)) {
    return [];
  }
  return readdirSync(profileDir)
    .filter((f) => f.endsWith(".profile.yaml"))
    .map((f) => ({
      file: f,
      path: join(profileDir, f),
      name: f.replace(".profile.yaml", ""),
    }));
}

// ---------------------------------------------------------------------------
// Disabled-agent root cleanup
//
// After stale managed files are removed, disabled-agent cleanup targets may
// remain on disk. Targets come in two forms:
//   - Directories (path ends with "/"): removed if empty, reported if
//     non-empty with unmanaged content.
//   - Files (no trailing "/"): removed if AJS-managed (provenance marker),
//     reported if unmanaged (operator-authored).
// ---------------------------------------------------------------------------

/**
 * Clean disabled-agent targets and report residuals.
 *
 * @param {Set<string>|null} enabledAgents — the set of enabled agent IDs, or null for all
 * @param {string} targetRoot — absolute path to the workspace root
 * @param {Map} agentRegistry — the agent registry Map
 * @param {{ purge?: boolean, backup?: boolean, stamp?: string }} [options]
 * @returns {{ removed: string[], residuals: { agentId: string, displayName: string, root: string }[], backedUp: { relativePath: string, backupPath: string }[] }}
 */
export function cleanDisabledAgentRoots(enabledAgents, targetRoot, agentRegistry, options = {}) {
  const removed = [];
  const residuals = [];
  const backedUp = [];
  const shouldPurge = Boolean(options.purge);
  const shouldBackup = Boolean(options.backup);
  const backupStamp = options.stamp ?? backupTimestamp();
  const resolvedTargetRoot = resolve(targetRoot);

  if (!enabledAgents) {
    return { removed, residuals, backedUp };
  }

  for (const [agentId, entry] of agentRegistry) {
    if (enabledAgents.has(agentId)) continue;
    for (const target of entry.agentRoots ?? []) {
      const targetPath = join(resolvedTargetRoot, target);
      if (!existsSync(targetPath)) continue;

      const isDirectoryTarget = target.endsWith("/");

      if (isDirectoryTarget) {
        try {
          if (!statSync(targetPath).isDirectory()) continue;
        } catch {
          continue;
        }

        const hasContent = directoryHasFiles(targetPath);
        if (!hasContent || shouldPurge) {
          const backupPath = removeTargetPath(targetPath, target, resolvedTargetRoot, {
            backup: shouldPurge && shouldBackup && hasContent,
            stamp: backupStamp,
          });
          if (backupPath) {
            backedUp.push({ relativePath: target, backupPath });
          }
          removed.push(target);
        } else {
          residuals.push({ agentId, displayName: entry.displayName, root: target });
        }
      } else {
        // File target (e.g. GEMINI.md, CONVENTIONS.md, .windsurfrules, .roorules, .clinerules)
        try {
          if (!statSync(targetPath).isFile()) continue;
        } catch {
          continue;
        }

        const kind = classifyExistingFile(targetPath);
        if (kind === "managed" || shouldPurge) {
          const backupPath = removeTargetPath(targetPath, target, resolvedTargetRoot, {
            backup: shouldPurge && shouldBackup && kind !== "managed",
            stamp: backupStamp,
          });
          if (backupPath) {
            backedUp.push({ relativePath: target, backupPath });
          }
          removed.push(target);
        } else {
          // Unmanaged operator-authored file — do not delete, report
          residuals.push({ agentId, displayName: entry.displayName, root: target });
        }
      }
    }
  }

  return { removed, residuals, backedUp };
}

function directoryHasFiles(dirPath) {
  try {
    const entries = readdirSync(dirPath);
    for (const entry of entries) {
      const entryPath = join(dirPath, entry);
      try {
        const stats = statSync(entryPath);
        if (stats.isFile()) return true;
        if (stats.isDirectory() && directoryHasFiles(entryPath)) return true;
      } catch {
        continue;
      }
    }
  } catch {
    return false;
  }
  return false;
}

export function listManagedFiles(rootPath) {
  const entries = [];

  function walk(currentPath) {
    for (const entry of readdirSync(currentPath)) {
      const absolutePath = join(currentPath, entry);
      const relativePath = relative(rootPath, absolutePath);
      const stats = statSync(absolutePath);
      if (stats.isDirectory()) {
        walk(absolutePath);
        continue;
      }
      entries.push(relativePath);
    }
  }

  walk(rootPath);
  return entries.sort();
}
