// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import { existsSync, readFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { readManagedPathsFromManifest } from "./files.mjs";
import { resolveLayeredSpec } from "./merging.mjs";
import { detectAgentJumpStartProvenance, findSkillCandidates, normalizeSkillSlug, parseSkillMdFrontmatter, readSkillDirectory, readSkillMdFile } from "./skills.mjs";
import { validateSkill, validateSkillMdFrontmatter } from "./validation.mjs";

export const KNOWN_SKILL_DIRS = [
  ".agents/skills",
  ".claude/skills",
  ".github/skills",
];

function normalizeValidationMessage(message, sourcePath) {
  return message
    .replace(/^Invalid SKILL\.md frontmatter:\s*/u, "")
    .replace(/^Validation failed:\s*/u, "")
    .replace(new RegExp(`^${escapeRegExp(sourcePath)}:\\s*`, "u"), "")
    .replace(new RegExp(`^Invalid skill(?: "[^"]+")? in ${escapeRegExp(sourcePath)}:\\s*`, "u"), "")
    .trim();
}

function extractErrorList(error, sourcePath) {
  const raw = error instanceof Error ? error.message : String(error);
  return raw
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => line !== "Invalid SKILL.md frontmatter:" && line !== "Validation failed:")
    .map((line) => line.replace(/^-+\s*/u, ""))
    .map((line) => normalizeValidationMessage(line, sourcePath))
    .filter(Boolean);
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Two-stage skill inspection used by both `intake` discovery and
 * `validate-skill`.
 *
 * Returns one of:
 *   { status: "import-compatible", slug, path, frontmatter, skill }
 *   { status: "generated-artifact", slug, path, frontmatter, provenance, errors }
 *                                                                    // Agent Jump Start render output; re-import would corrupt the spec
 *   { status: "structurally-valid", slug, path, frontmatter, errors }  // frontmatter ok, canonical rebuild failed
 *   { status: "frontmatter-invalid", slug, path, errors }              // missing/invalid SKILL.md or frontmatter
 *
 * The caller can collapse the three invalid statuses into a single "invalid"
 * bucket if it does not care about which stage failed (e.g. intake discovery),
 * but `generated-artifact` carries an extra `provenance` field so callers can
 * point operators at the raw source.
 */
export function inspectSkillSource(skillPath) {
  const absolutePath = resolve(skillPath);
  const isDirectory = existsSync(join(absolutePath, "SKILL.md"));
  const skillMdPath = isDirectory ? join(absolutePath, "SKILL.md") : absolutePath;
  const fallbackSlug = basename(isDirectory ? absolutePath : absolutePath.replace(/\.md$/i, ""));

  if (!existsSync(skillMdPath)) {
    return {
      slug: fallbackSlug,
      path: absolutePath,
      status: "frontmatter-invalid",
      errors: [isDirectory ? "No SKILL.md found in skill directory." : "Skill source not found."],
    };
  }

  const content = readFileSync(skillMdPath, "utf8");
  const { frontmatter } = parseSkillMdFrontmatter(content);
  const discoveredSlug = frontmatter?.name ? normalizeSkillSlug(frontmatter.name) : fallbackSlug;

  // Check Agent Jump Start provenance before any canonical rebuild: a rendered
  // SKILL.md can still have syntactically-valid frontmatter and body, but
  // feeding it back through readExternalSkill would collapse it into the
  // recursive `rcbp-*` / `qr-*` / `dg-*` corruption pattern described in P0-0.
  const provenance = detectAgentJumpStartProvenance(content, frontmatter);
  if (provenance) {
    const fromHint = provenance.generatedFrom ? ` from \`${provenance.generatedFrom}\`` : "";
    return {
      slug: discoveredSlug,
      path: absolutePath,
      status: "generated-artifact",
      frontmatter,
      provenance,
      errors: [
        `This SKILL.md was generated by Agent Jump Start v${provenance.version}${fromHint}.`,
        "Re-importing generated artifacts corrupts the canonical spec (synthetic categories, recursive rule ids).",
        "Import the raw upstream skill instead, or run `agent-jump-start update-skills` to refresh from its tracked source.",
      ],
    };
  }

  if (!frontmatter) {
    return {
      slug: discoveredSlug,
      path: absolutePath,
      status: "frontmatter-invalid",
      errors: ["SKILL.md has no YAML frontmatter block."],
    };
  }

  const frontmatterErrors = validateSkillMdFrontmatter(frontmatter, skillMdPath)
    .map((error) => normalizeValidationMessage(error, skillMdPath));
  if (frontmatterErrors.length > 0) {
    return {
      slug: discoveredSlug,
      path: absolutePath,
      status: "frontmatter-invalid",
      errors: frontmatterErrors,
    };
  }

  try {
    const skill = isDirectory ? readSkillDirectory(absolutePath) : readSkillMdFile(absolutePath);
    validateSkill(skill, absolutePath);
    return {
      slug: skill.slug,
      path: absolutePath,
      status: "import-compatible",
      frontmatter,
      skill,
    };
  } catch (error) {
    return {
      slug: discoveredSlug,
      path: absolutePath,
      status: "structurally-valid",
      frontmatter,
      errors: extractErrorList(error, absolutePath),
    };
  }
}

export function inspectSkillDirectory(skillDir) {
  return inspectSkillSource(skillDir);
}

function inspectSkillCandidate(skillDir) {
  const inspected = inspectSkillSource(skillDir);
  if (inspected.status === "import-compatible") {
    return {
      slug: inspected.skill.slug,
      path: inspected.path,
      status: "valid",
      skill: inspected.skill,
    };
  }
  if (inspected.status === "generated-artifact") {
    return {
      slug: inspected.slug,
      path: inspected.path,
      status: "invalid",
      errors: inspected.errors,
      provenanceType: "agent-jump-start",
      provenance: inspected.provenance,
    };
  }
  return {
    slug: inspected.slug,
    path: inspected.path,
    status: "invalid",
    errors: inspected.errors,
  };
}

export function discoverUnmanagedSkills(targetRoot, specInput) {
  const absoluteRoot = resolve(targetRoot);
  const spec = typeof specInput === "string" ? resolveLayeredSpec(specInput) : specInput;
  const managedSlugs = new Set((spec.skills ?? []).map((skill) => skill.slug));
  const manifestManagedPaths = readManagedPathsFromManifest(absoluteRoot);
  const discoveries = [];
  const seenSlugs = new Set();

  for (const relativeDir of KNOWN_SKILL_DIRS) {
    const scanRoot = join(absoluteRoot, relativeDir);
    const candidates = findSkillCandidates(scanRoot).sort((a, b) => a.localeCompare(b));

    for (const candidate of candidates) {
      const skillMdRelativePath = join(relativeDir, basename(candidate), "SKILL.md").replaceAll("\\", "/");
      if (manifestManagedPaths.has(skillMdRelativePath)) {
        continue;
      }

      const inspected = inspectSkillCandidate(candidate);
      if (seenSlugs.has(inspected.slug)) {
        continue;
      }
      seenSlugs.add(inspected.slug);

      if (inspected.status === "invalid") {
        discoveries.push(inspected);
        continue;
      }

      discoveries.push({
        slug: inspected.skill.slug,
        path: inspected.path,
        status: managedSlugs.has(inspected.skill.slug) ? "managed" : "unmanaged",
      });
    }
  }

  return discoveries.sort((a, b) => a.slug.localeCompare(b.slug));
}
