// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import { relative, resolve } from "node:path";
import { TOOL_VERSION, AGENT_COUNT } from "./constants.mjs";
import { formatBulletList, truncateAtWordBoundary, renderYamlObjectLines } from "./utils.mjs";

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function generatedNotice(specRelativePath) {
  return `> Generated by Agent Jump Start v${TOOL_VERSION} from \`${specRelativePath}\`.\n> Update the canonical spec and rerun \`render\` instead of hand-editing this file.\n`;
}

export function buildSkillDiscoveryDescription(skill, maxLength = 200) {
  const base = skill.description.trim();
  const usageHint = skill.appliesWhen
    .map((entry) => entry.trim())
    .filter(Boolean)
    .slice(0, 3)
    .join("; ");

  if (!usageHint) {
    return truncateAtWordBoundary(base, maxLength);
  }

  return truncateAtWordBoundary(`${base} Use when: ${usageHint}.`, maxLength);
}

function sortedCategories(categories) {
  return [...categories].sort((left, right) =>
    left.priority - right.priority || left.name.localeCompare(right.name),
  );
}

function groupRulesByCategory(skill) {
  return sortedCategories(skill.categories).map((category) => ({
    ...category,
    rules: skill.rules.filter((rule) => rule.category === category.name),
  }));
}

// ---------------------------------------------------------------------------
// Skill content renderers
// ---------------------------------------------------------------------------

function renderCategoryTable(categories) {
  const lines = [
    "| Priority | Category | Impact | Prefix |",
    "|----------|----------|--------|--------|",
  ];
  for (const category of sortedCategories(categories)) {
    lines.push(
      `| ${category.priority} | ${category.name} | ${category.impact} | \`${category.prefix}\` |`,
    );
  }
  return lines.join("\n");
}

function renderQuickReference(skill) {
  const lines = [];
  for (const category of groupRulesByCategory(skill)) {
    lines.push(`### ${category.priority}. ${category.name} (${category.impact})`, "");
    for (const rule of category.rules) {
      lines.push(`- \`${rule.id}\` - ${rule.summary}`);
    }
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}

function renderDetailedGuidance(skill) {
  const lines = ["## Detailed Guidance", ""];
  for (const category of groupRulesByCategory(skill)) {
    lines.push(`### ${category.name}`, "");
    for (const rule of category.rules) {
      lines.push(`#### ${rule.id} - ${rule.title}`, "");
      lines.push(`**Impact:** ${rule.impact}`, "");
      lines.push(rule.summary, "");
      if (rule.guidance?.length) {
        lines.push(formatBulletList(rule.guidance), "");
      }
    }
  }
  return lines.join("\n").trimEnd();
}

function renderSkillSummarySection(skill) {
  const lines = [
    `### ${skill.title}`,
    "",
    `**Version ${skill.version}**${skill.author ? ` — ${skill.author}` : ""}`,
    "",
    skill.description,
    "",
    "**When to apply:** " + skill.appliesWhen.join("; "),
    "",
    renderQuickReference(skill),
    "",
  ];
  return lines.join("\n").trimEnd();
}

// ---------------------------------------------------------------------------
// Reference table renderer
// ---------------------------------------------------------------------------

function renderReferenceTable(skill, skillDir) {
  if (!skill.references?.length) return "";

  const lines = [
    "## Reference Guide",
    "",
    "Load detailed guidance based on context:",
    "",
    "| Topic | Reference | Load When |",
    "|-------|-----------|-----------|",
  ];

  for (const ref of skill.references) {
    const topic = ref.name.replace(/\.md$/, "").replace(/[-_]/g, " ");
    const loadWhen = ref.loadWhen ?? topic;
    lines.push(`| ${topic} | \`${skillDir}/references/${ref.name}\` | ${loadWhen} |`);
  }

  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// SKILL.md rendering
// ---------------------------------------------------------------------------

function renderSkillBody(skill, specRelativePath, { includeCompatibilityNotice = false, skillDir = null } = {}) {
  const lines = [`# ${skill.title}`, ""];

  if (skill.author) {
    lines.push(`**Version ${skill.version}**  `, skill.author, "");
  } else {
    lines.push(`**Version ${skill.version}**`, "");
  }

  if (includeCompatibilityNotice) {
    lines.push(
      "> Compatibility note: `SKILL.md` is the canonical, Agent Skills-compatible entrypoint for this skill.",
      "",
    );
  }

  lines.push(
    generatedNotice(specRelativePath).trimEnd(),
    "",
    "## Overview",
    "",
    skill.description,
    "",
    "## When to Use This Skill",
    "",
    formatBulletList(skill.appliesWhen),
    "",
  );

  // Reference table (progressive disclosure)
  if (skill.references?.length && skillDir) {
    lines.push(renderReferenceTable(skill, skillDir));
  }

  lines.push(
    "## Rule Categories by Priority",
    "",
    renderCategoryTable(skill.categories),
    "",
    "## Quick Reference",
    "",
    renderQuickReference(skill),
    "",
    renderDetailedGuidance(skill),
    "",
  );

  return `${lines.join("\n").trimEnd()}\n`;
}

function renderSkillFrontmatter(skill, specRelativePath) {
  const metadata = {
    title: skill.title,
    version: skill.version,
    author: skill.author,
    generated_by: `Agent Jump Start v${TOOL_VERSION}`,
    generated_from: specRelativePath,
    ...skill.metadata,
  };

  const frontmatter = {
    name: skill.slug,
    description: buildSkillDiscoveryDescription(skill),
    license: skill.license ?? "MPL-2.0",
    dependencies: skill.dependencies,
    metadata,
  };

  return `---\n${renderYamlObjectLines(frontmatter).join("\n")}\n---\n`;
}

function renderSkillFile(skill, specRelativePath, skillDir = null) {
  return `${renderSkillFrontmatter(skill, specRelativePath)}\n${renderSkillBody(skill, specRelativePath, { skillDir })}`;
}

function renderLegacySkillGuide(skill, specRelativePath) {
  return renderSkillBody(skill, specRelativePath, { includeCompatibilityNotice: true });
}

// ---------------------------------------------------------------------------
// Workspace instruction renderers
// ---------------------------------------------------------------------------

function renderWorkspaceInstructions(spec, specRelativePath, { includeSkillSummaries = false } = {}) {
  const lines = [
    "# Workspace Instructions",
    "",
    generatedNotice(specRelativePath).trimEnd(),
    "",
  ];

  const workspace = spec.workspaceInstructions;
  if (workspace.packageManagerRule) {
    lines.push(workspace.packageManagerRule, "");
  }
  if (workspace.runtimeRule) {
    lines.push(workspace.runtimeRule, "");
  }
  if (spec.project?.components?.length) {
    lines.push("This workspace contains:");
    for (const component of spec.project.components) {
      lines.push(`- ${component}`);
    }
    lines.push("");
  }

  for (const section of workspace.sections ?? []) {
    lines.push(`${section.title}:`);
    lines.push(formatBulletList(section.rules));
    lines.push("");
  }

  if (workspace.validation?.length) {
    lines.push("Validation rules:");
    lines.push(formatBulletList(workspace.validation));
    lines.push("");
  }

  if (includeSkillSummaries && spec.skills?.length) {
    lines.push("## Skills", "");
    for (const skill of spec.skills) {
      lines.push(renderSkillSummarySection(skill), "");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

// ---------------------------------------------------------------------------
// Cursor MDC renderers
// ---------------------------------------------------------------------------

function renderCursorMdc(spec, specRelativePath) {
  const workspace = spec.workspaceInstructions;
  const bodyLines = [];

  if (workspace.packageManagerRule) {
    bodyLines.push(workspace.packageManagerRule, "");
  }
  if (workspace.runtimeRule) {
    bodyLines.push(workspace.runtimeRule, "");
  }
  if (spec.project?.components?.length) {
    bodyLines.push("This workspace contains:");
    for (const component of spec.project.components) {
      bodyLines.push(`- ${component}`);
    }
    bodyLines.push("");
  }

  for (const section of workspace.sections ?? []) {
    bodyLines.push(`## ${section.title}`, "");
    bodyLines.push(formatBulletList(section.rules));
    bodyLines.push("");
  }

  if (workspace.validation?.length) {
    bodyLines.push("## Validation rules", "");
    bodyLines.push(formatBulletList(workspace.validation));
    bodyLines.push("");
  }

  const description = spec.project?.summary ?? "Workspace instructions generated by Agent Jump Start";

  const lines = [
    "---",
    `description: ${description}`,
    "alwaysApply: true",
    "---",
    "",
    `# ${spec.project?.name ?? "Workspace Instructions"}`,
    "",
    `> Generated by Agent Jump Start v${TOOL_VERSION} from \`${specRelativePath}\`.`,
    "",
    ...bodyLines,
  ];

  return `${lines.join("\n").trimEnd()}\n`;
}

function renderCursorSkillMdc(skill, specRelativePath) {
  const versionLine = skill.author
    ? `**Version ${skill.version}** - ${skill.author}`
    : `**Version ${skill.version}**`;
  const lines = [
    "---",
    `description: ${buildSkillDiscoveryDescription(skill)}`,
    "alwaysApply: false",
    "---",
    "",
    `# ${skill.title}`,
    "",
    `> Generated by Agent Jump Start v${TOOL_VERSION} from \`${specRelativePath}\`.`,
    "",
    versionLine,
    "",
    "## When to Apply",
    "",
    formatBulletList(skill.appliesWhen),
    "",
    "## Quick Reference",
    "",
    renderQuickReference(skill),
    "",
    renderDetailedGuidance(skill),
    "",
  ];

  return `${lines.join("\n").trimEnd()}\n`;
}

// ---------------------------------------------------------------------------
// Review checklist
// ---------------------------------------------------------------------------

function renderReviewChecklist(spec, specRelativePath) {
  const references = [
    "AGENTS.md",
    "CLAUDE.md",
    ".github/copilot-instructions.md",
    ".cursor/rules/agent-instructions.mdc",
    ".windsurfrules",
    ".clinerules",
    ".roo/rules/agent-instructions.md",
    ".continue/rules/agent-instructions.md",
    "CONVENTIONS.md",
    ...(spec.skills ?? []).flatMap((skill) => [
      `.agents/skills/${skill.slug}/SKILL.md`,
      `.claude/skills/${skill.slug}/SKILL.md`,
      `.github/skills/${skill.slug}/SKILL.md`,
      `.agents/skills/${skill.slug}/AGENTS.md`,
      `.claude/skills/${skill.slug}/AGENTS.md`,
      `.cursor/rules/${skill.slug}.mdc`,
    ]),
  ];
  const checklist = spec.reviewChecklist;
  const lines = [
    "# Review Checklist For Agents",
    "",
    generatedNotice(specRelativePath).trimEnd(),
    "",
    checklist.intro,
    "",
    "## Usage",
    "",
    `Treat a response or proposal as misaligned if it fails ${checklist.failureThreshold} or more checks without a deliberate reason.`,
    "",
    "## Checklist",
    "",
  ];

  checklist.items.forEach((item, index) => {
    lines.push(`${index + 1}. ${item.title}`, "");
    for (const detail of item.details ?? []) {
      lines.push(`   ${detail}`, "");
    }
  });

  if (checklist.quickSignals?.length) {
    lines.push("## Quick Signals", "");
    lines.push(formatBulletList(checklist.quickSignals), "");
  }

  if (checklist.redFlags?.length) {
    lines.push("## Red Flags", "");
    lines.push(formatBulletList(checklist.redFlags), "");
  }

  lines.push("## References", "");
  lines.push(formatBulletList(references), "");

  return `${lines.join("\n").trimEnd()}\n`;
}

// ---------------------------------------------------------------------------
// Main orchestrator: generate all files from a spec
// ---------------------------------------------------------------------------

export function renderGeneratedFiles(spec, specPath, targetRoot) {
  const specAbsolutePath = resolve(specPath);
  const targetAbsolutePath = resolve(targetRoot);
  const specRelativePath = relative(targetAbsolutePath, specAbsolutePath) || specPath;
  const generatedFiles = {};

  const workspaceDoc = renderWorkspaceInstructions(spec, specRelativePath);
  const workspaceDocWithSkills = renderWorkspaceInstructions(spec, specRelativePath, { includeSkillSummaries: true });

  // --- Agents with native skill folder support (get workspace-only doc) ---
  generatedFiles["AGENTS.md"] = workspaceDoc;
  generatedFiles["CLAUDE.md"] = workspaceDoc;
  generatedFiles[".github/copilot-instructions.md"] = workspaceDoc;

  // --- Cursor (MDC format with frontmatter) ---
  generatedFiles[".cursor/rules/agent-instructions.mdc"] = renderCursorMdc(spec, specRelativePath);

  // --- Agents WITHOUT native skill folders (get workspace doc + inline skill summaries) ---
  generatedFiles[".windsurfrules"] = workspaceDocWithSkills;
  generatedFiles[".clinerules"] = workspaceDocWithSkills;
  generatedFiles[".roo/rules/agent-instructions.md"] = workspaceDocWithSkills;
  generatedFiles[".continue/rules/agent-instructions.md"] = workspaceDocWithSkills;
  generatedFiles["CONVENTIONS.md"] = workspaceDocWithSkills;

  // --- Skills ---
  for (const skill of spec.skills ?? []) {
    const agentsSkillDir = `.agents/skills/${skill.slug}`;
    const claudeSkillDir = `.claude/skills/${skill.slug}`;
    const githubSkillDir = `.github/skills/${skill.slug}`;

    const agentsSkillFile = renderSkillFile(skill, specRelativePath, agentsSkillDir);
    const claudeSkillFile = renderSkillFile(skill, specRelativePath, claudeSkillDir);
    const githubSkillFile = renderSkillFile(skill, specRelativePath, githubSkillDir);
    generatedFiles[`${agentsSkillDir}/SKILL.md`] = agentsSkillFile;
    generatedFiles[`${claudeSkillDir}/SKILL.md`] = claudeSkillFile;
    generatedFiles[`${githubSkillDir}/SKILL.md`] = githubSkillFile;

    const guide = renderLegacySkillGuide(skill, specRelativePath);
    generatedFiles[`${agentsSkillDir}/AGENTS.md`] = guide;
    generatedFiles[`${claudeSkillDir}/AGENTS.md`] = guide;

    // Cursor skill files (MDC format)
    generatedFiles[`.cursor/rules/${skill.slug}.mdc`] = renderCursorSkillMdc(skill, specRelativePath);

    // Skill references (progressive disclosure)
    if (skill.references?.length) {
      for (const ref of skill.references) {
        generatedFiles[`${agentsSkillDir}/references/${ref.name}`] = ref.content;
        generatedFiles[`${claudeSkillDir}/references/${ref.name}`] = ref.content;
        generatedFiles[`${githubSkillDir}/references/${ref.name}`] = ref.content;
      }
    }
  }

  // --- Review Checklist ---
  if (spec.reviewChecklist) {
    generatedFiles["docs/agent-review-checklist.md"] = renderReviewChecklist(spec, specRelativePath);
  }

  // --- Manifest ---
  const manifestPath = "docs/agent-jump-start/generated-manifest.json";
  generatedFiles[manifestPath] = `${JSON.stringify(
    {
      generatedFrom: specRelativePath,
      generatorVersion: TOOL_VERSION,
      agents: [
        "Claude Code", "GitHub Copilot", "GitHub Agents", "Cursor",
        "Windsurf", "Cline", "Roo Code", "Continue.dev", "Aider",
      ],
      files: Object.keys(generatedFiles).sort(),
    },
    null,
    2,
  )}\n`;

  return generatedFiles;
}
