// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import { relative, resolve } from "node:path";
import { TOOL_VERSION, AGENT_COUNT } from "./constants.mjs";
import { formatBulletList, truncateAtWordBoundary, renderYamlObjectLines } from "./utils.mjs";

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function generatedNotice(specRelativePath) {
  return `> Generated by Agent Jump Start v${TOOL_VERSION} from \`${specRelativePath}\`.\n> Update the canonical spec and rerun \`render\` instead of hand-editing this file.\n`;
}

export function buildSkillDiscoveryDescription(skill, maxLength = 200) {
  const base = skill.description.trim();
  const usageHint = skill.appliesWhen
    .map((entry) => entry.trim())
    .filter(Boolean)
    .slice(0, 3)
    .join("; ");

  if (!usageHint) {
    return truncateAtWordBoundary(base, maxLength);
  }

  return truncateAtWordBoundary(`${base} Use when: ${usageHint}.`, maxLength);
}

function sortedCategories(categories) {
  return [...categories].sort((left, right) =>
    left.priority - right.priority || left.name.localeCompare(right.name),
  );
}

function groupRulesByCategory(skill) {
  return sortedCategories(skill.categories).map((category) => ({
    ...category,
    rules: skill.rules.filter((rule) => rule.category === category.name),
  }));
}

// ---------------------------------------------------------------------------
// Skill content renderers
// ---------------------------------------------------------------------------

function renderCategoryTable(categories) {
  const lines = [
    "| Priority | Category | Impact | Prefix |",
    "|----------|----------|--------|--------|",
  ];
  for (const category of sortedCategories(categories)) {
    lines.push(
      `| ${category.priority} | ${category.name} | ${category.impact} | \`${category.prefix}\` |`,
    );
  }
  return lines.join("\n");
}

function renderQuickReference(skill) {
  const lines = [];
  for (const category of groupRulesByCategory(skill)) {
    lines.push(`### ${category.priority}. ${category.name} (${category.impact})`, "");
    for (const rule of category.rules) {
      lines.push(`- \`${rule.id}\` - ${rule.summary}`);
    }
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}

function renderDetailedGuidance(skill) {
  const lines = ["## Detailed Guidance", ""];
  for (const category of groupRulesByCategory(skill)) {
    lines.push(`### ${category.name}`, "");
    for (const rule of category.rules) {
      const semanticTag = rule.semantic === "prohibition" ? " [PROHIBITION]" :
                          rule.semantic === "workflow" ? " [WORKFLOW]" :
                          rule.semantic === "example" ? " [EXAMPLE]" : "";
      lines.push(`#### ${rule.id} - ${rule.title}${semanticTag}`, "");
      lines.push(`**Impact:** ${rule.impact}`, "");
      if (rule.semantic === "prohibition") {
        lines.push(`> **MUST NOT:** ${rule.summary}`, "");
      } else {
        lines.push(rule.summary, "");
      }
      if (rule.guidance?.length) {
        lines.push(formatBulletList(rule.guidance), "");
      }
    }
  }
  return lines.join("\n").trimEnd();
}

function renderSkillSummarySection(skill) {
  const lines = [
    `### ${skill.title}`,
    "",
    `**Version ${skill.version}**${skill.author ? ` — ${skill.author}` : ""}`,
    "",
    skill.description,
    "",
    "**When to apply:** " + skill.appliesWhen.join("; "),
    "",
    renderQuickReference(skill),
    "",
  ];
  return lines.join("\n").trimEnd();
}

// ---------------------------------------------------------------------------
// Reference / scripts / assets table renderers
// ---------------------------------------------------------------------------

function renderReferenceTable(skill, referenceBasePath = "references") {
  if (!skill.references?.length) return "";

  const lines = [
    "## Reference Guide",
    "",
    "Load detailed guidance based on context:",
    "",
    "| Topic | Reference | Load When |",
    "|-------|-----------|-----------|",
  ];

  for (const ref of skill.references) {
    const topic = ref.name.replace(/\.md$/, "").replace(/[-_]/g, " ");
    const loadWhen = ref.loadWhen ?? topic;
    lines.push(`| ${topic} | \`${referenceBasePath}/${ref.name}\` | ${loadWhen} |`);
  }

  lines.push("");
  return lines.join("\n");
}

function renderScriptsTable(skill, scriptsBasePath = "scripts") {
  if (!skill.scripts?.length) return "";

  const lines = [
    "## Bundled Scripts",
    "",
    "Executable scripts available for this skill:",
    "",
    "| Script | Path | Description |",
    "|--------|------|-------------|",
  ];

  for (const script of skill.scripts) {
    const label = script.name.replace(/[-_]/g, " ").replace(/\.[^.]+$/, "");
    const description = script.description ?? label;
    lines.push(`| ${label} | \`${scriptsBasePath}/${script.name}\` | ${description} |`);
  }

  lines.push("");
  return lines.join("\n");
}

function renderAssetsTable(skill, assetsBasePath = "assets") {
  if (!skill.assets?.length) return "";

  const lines = [
    "## Assets",
    "",
    "Static resources bundled with this skill:",
    "",
    "| Asset | Path | Description |",
    "|-------|------|-------------|",
  ];

  for (const asset of skill.assets) {
    const label = asset.name.replace(/[-_]/g, " ").replace(/\.[^.]+$/, "");
    const description = asset.description ?? label;
    lines.push(`| ${label} | \`${assetsBasePath}/${asset.name}\` | ${description} |`);
  }

  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// SKILL.md rendering
// ---------------------------------------------------------------------------

function renderSkillBody(
  skill,
  specRelativePath,
  { includeCompatibilityNotice = false, referenceBasePath = null, scriptsBasePath = null, assetsBasePath = null } = {},
) {
  const lines = [`# ${skill.title}`, ""];

  if (skill.author) {
    lines.push(`**Version ${skill.version}**  `, skill.author, "");
  } else {
    lines.push(`**Version ${skill.version}**`, "");
  }

  if (includeCompatibilityNotice) {
    lines.push(
      "> Compatibility note: `SKILL.md` is the canonical, Agent Skills-compatible entrypoint for this skill.",
      "",
    );
  }

  lines.push(
    generatedNotice(specRelativePath).trimEnd(),
    "",
    "## Overview",
    "",
    skill.description,
    "",
    "## When to Use This Skill",
    "",
    formatBulletList(skill.appliesWhen),
    "",
  );

  // Reference table (progressive disclosure)
  if (skill.references?.length && referenceBasePath) {
    lines.push(renderReferenceTable(skill, referenceBasePath));
  }

  // Scripts table (progressive disclosure)
  if (skill.scripts?.length && scriptsBasePath) {
    lines.push(renderScriptsTable(skill, scriptsBasePath));
  }

  // Assets table (progressive disclosure)
  if (skill.assets?.length && assetsBasePath) {
    lines.push(renderAssetsTable(skill, assetsBasePath));
  }

  lines.push(
    "## Rule Categories by Priority",
    "",
    renderCategoryTable(skill.categories),
    "",
    "## Quick Reference",
    "",
    renderQuickReference(skill),
    "",
    renderDetailedGuidance(skill),
    "",
  );

  return `${lines.join("\n").trimEnd()}\n`;
}

function renderSkillFrontmatter(skill, specRelativePath) {
  const metadata = {
    title: skill.title,
    version: skill.version,
    author: skill.author,
    generated_by: `Agent Jump Start v${TOOL_VERSION}`,
    generated_from: specRelativePath,
    ...skill.metadata,
  };

  const frontmatter = {
    name: skill.slug,
    description: buildSkillDiscoveryDescription(skill),
    license: skill.license ?? "MPL-2.0",
  };

  // Trigger and activation metadata — top-level frontmatter for ecosystem compatibility
  if (skill.triggers?.length) frontmatter.triggers = skill.triggers;
  if (skill.globs?.length) frontmatter.globs = skill.globs;
  if (skill.alwaysApply !== undefined) frontmatter.alwaysApply = skill.alwaysApply;
  if (skill.manualOnly !== undefined) frontmatter.manualOnly = skill.manualOnly;
  if (skill.relatedSkills?.length) frontmatter.relatedSkills = skill.relatedSkills;
  if (skill.compatibility?.length) frontmatter.compatibility = skill.compatibility;

  if (skill.dependencies?.length) frontmatter.dependencies = skill.dependencies;
  frontmatter.metadata = metadata;

  return `---\n${renderYamlObjectLines(frontmatter).join("\n")}\n---\n`;
}

function renderSkillFile(skill, specRelativePath, referenceBasePath = "references") {
  return `${renderSkillFrontmatter(skill, specRelativePath)}\n${renderSkillBody(skill, specRelativePath, { referenceBasePath, scriptsBasePath: "scripts", assetsBasePath: "assets" })}`;
}

function renderLegacySkillGuide(skill, specRelativePath) {
  return renderSkillBody(skill, specRelativePath, { includeCompatibilityNotice: true });
}

function buildCanonicalSkillPackage(skill, specRelativePath) {
  const canonicalPackageFiles = {
    "SKILL.md": renderSkillFile(skill, specRelativePath),
    "AGENTS.md": renderLegacySkillGuide(skill, specRelativePath),
  };

  if (skill.references?.length) {
    for (const ref of skill.references) {
      canonicalPackageFiles[`references/${ref.name}`] = ref.content;
    }
  }

  if (skill.scripts?.length) {
    for (const script of skill.scripts) {
      canonicalPackageFiles[`scripts/${script.name}`] = script.content;
    }
  }

  if (skill.assets?.length) {
    for (const asset of skill.assets) {
      canonicalPackageFiles[`assets/${asset.name}`] = asset.content;
    }
  }

  return canonicalPackageFiles;
}

function mountSkillPackage(generatedFiles, baseDir, packageFiles, { includeLegacyGuide = false } = {}) {
  for (const [relativePath, content] of Object.entries(packageFiles)) {
    if (!includeLegacyGuide && relativePath === "AGENTS.md") {
      continue;
    }
    generatedFiles[`${baseDir}/${relativePath}`] = content;
  }
}

// ---------------------------------------------------------------------------
// Workspace instruction renderers
// ---------------------------------------------------------------------------

function canonicalSourceNotice(canonicalPath) {
  return `> This file is a compatibility mirror of [\`${canonicalPath}\`](${canonicalPath}).\n> Edit the canonical spec and rerun \`render\` — do not hand-edit this file or its canonical source independently.\n`;
}

function renderWorkspaceInstructions(spec, specRelativePath, { includeSkillSummaries = false, mirrorOf = null } = {}) {
  const lines = [
    "# Workspace Instructions",
    "",
  ];

  if (mirrorOf) {
    lines.push(canonicalSourceNotice(mirrorOf).trimEnd(), "");
  }

  lines.push(generatedNotice(specRelativePath).trimEnd(), "");

  const workspace = spec.workspaceInstructions;
  if (workspace.packageManagerRule) {
    lines.push(workspace.packageManagerRule, "");
  }
  if (workspace.runtimeRule) {
    lines.push(workspace.runtimeRule, "");
  }
  if (spec.project?.components?.length) {
    lines.push("This workspace contains:");
    for (const component of spec.project.components) {
      lines.push(`- ${component}`);
    }
    lines.push("");
  }

  for (const section of workspace.sections ?? []) {
    lines.push(`${section.title}:`);
    lines.push(formatBulletList(section.rules));
    lines.push("");
  }

  if (workspace.validation?.length) {
    lines.push("Validation rules:");
    lines.push(formatBulletList(workspace.validation));
    lines.push("");
  }

  if (includeSkillSummaries && spec.skills?.length) {
    lines.push("## Skills", "");
    for (const skill of spec.skills) {
      lines.push(renderSkillSummarySection(skill), "");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

// ---------------------------------------------------------------------------
// Cursor MDC renderers
// ---------------------------------------------------------------------------

function renderCursorMdc(spec, specRelativePath) {
  const workspace = spec.workspaceInstructions;
  const bodyLines = [];

  if (workspace.packageManagerRule) {
    bodyLines.push(workspace.packageManagerRule, "");
  }
  if (workspace.runtimeRule) {
    bodyLines.push(workspace.runtimeRule, "");
  }
  if (spec.project?.components?.length) {
    bodyLines.push("This workspace contains:");
    for (const component of spec.project.components) {
      bodyLines.push(`- ${component}`);
    }
    bodyLines.push("");
  }

  for (const section of workspace.sections ?? []) {
    bodyLines.push(`## ${section.title}`, "");
    bodyLines.push(formatBulletList(section.rules));
    bodyLines.push("");
  }

  if (workspace.validation?.length) {
    bodyLines.push("## Validation rules", "");
    bodyLines.push(formatBulletList(workspace.validation));
    bodyLines.push("");
  }

  const description = spec.project?.summary ?? "Workspace instructions generated by Agent Jump Start";

  const lines = [
    "---",
    `description: ${description}`,
    "alwaysApply: true",
    "---",
    "",
    `# ${spec.project?.name ?? "Workspace Instructions"}`,
    "",
    `> Generated by Agent Jump Start v${TOOL_VERSION} from \`${specRelativePath}\`.`,
    "",
    ...bodyLines,
  ];

  return `${lines.join("\n").trimEnd()}\n`;
}

function renderCursorSkillMdc(skill, specRelativePath) {
  const versionLine = skill.author
    ? `**Version ${skill.version}** - ${skill.author}`
    : `**Version ${skill.version}**`;

  // Cursor MDC frontmatter: project alwaysApply and globs from trigger metadata
  const cursorAlwaysApply = skill.alwaysApply === true ? "true" : "false";
  const cursorGlobs = skill.globs?.length ? skill.globs.join(", ") : null;

  const lines = [
    "---",
    `description: ${buildSkillDiscoveryDescription(skill)}`,
    `alwaysApply: ${cursorAlwaysApply}`,
  ];
  if (cursorGlobs) {
    lines.push(`globs: ${cursorGlobs}`);
  }
  lines.push(
    "---",
    "",
    `# ${skill.title}`,
    "",
    `> Generated by Agent Jump Start v${TOOL_VERSION} from \`${specRelativePath}\`.`,
    "",
    versionLine,
    "",
    "## When to Apply",
    "",
    formatBulletList(skill.appliesWhen),
    "",
    "## Quick Reference",
    "",
    renderQuickReference(skill),
    "",
    renderDetailedGuidance(skill),
    "",
  );

  return `${lines.join("\n").trimEnd()}\n`;
}

// ---------------------------------------------------------------------------
// Review checklist
// ---------------------------------------------------------------------------

function renderReviewChecklist(spec, specRelativePath) {
  const references = [
    ".agents/AGENTS.md",
    "AGENTS.md",
    "AGENT.md",
    "CLAUDE.md",
    "GEMINI.md",
    ".github/copilot-instructions.md",
    ".github/instructions/general.instructions.md",
    ".cursor/rules/agent-instructions.mdc",
    ".windsurf/rules/general.md",
    ".windsurfrules",
    ".clinerules/general.md",
    ".roo/rules/agent-instructions.md",
    ".roorules",
    ".continue/rules/agent-instructions.md",
    ".amazonq/rules/general.md",
    ".junie/AGENTS.md",
    ".junie/guidelines.md",
    "CONVENTIONS.md",
    ...(spec.skills ?? []).flatMap((skill) => [
      `.agents/skills/${skill.slug}/SKILL.md`,
      `.claude/skills/${skill.slug}/SKILL.md`,
      `.github/skills/${skill.slug}/SKILL.md`,
      `.agents/skills/${skill.slug}/AGENTS.md`,
      `.claude/skills/${skill.slug}/AGENTS.md`,
      `.cursor/rules/${skill.slug}.mdc`,
    ]),
  ];
  const checklist = spec.reviewChecklist;
  const lines = [
    "# Review Checklist For Agents",
    "",
    generatedNotice(specRelativePath).trimEnd(),
    "",
    checklist.intro,
    "",
    "## Usage",
    "",
    `Treat a response or proposal as misaligned if it fails ${checklist.failureThreshold} or more checks without a deliberate reason.`,
    "",
    "## Checklist",
    "",
  ];

  checklist.items.forEach((item, index) => {
    lines.push(`${index + 1}. ${item.title}`, "");
    for (const detail of item.details ?? []) {
      lines.push(`   ${detail}`, "");
    }
  });

  if (checklist.quickSignals?.length) {
    lines.push("## Quick Signals", "");
    lines.push(formatBulletList(checklist.quickSignals), "");
  }

  if (checklist.redFlags?.length) {
    lines.push("## Red Flags", "");
    lines.push(formatBulletList(checklist.redFlags), "");
  }

  lines.push("## References", "");
  lines.push(formatBulletList(references), "");

  return `${lines.join("\n").trimEnd()}\n`;
}

// ---------------------------------------------------------------------------
// Main orchestrator: generate all files from a spec
// ---------------------------------------------------------------------------

export function renderGeneratedFiles(spec, specPath, targetRoot) {
  const specAbsolutePath = resolve(specPath);
  const targetAbsolutePath = resolve(targetRoot);
  const specRelativePath = relative(targetAbsolutePath, specAbsolutePath) || specPath;
  const generatedFiles = {};

  // --- Canonical workspace governance file ---
  const canonicalPath = ".agents/AGENTS.md";
  const canonicalDoc = renderWorkspaceInstructions(spec, specRelativePath);
  generatedFiles[canonicalPath] = canonicalDoc;

  // --- Canonical mirrors (workspace-level instruction file variants) ---
  const nativeMirrorDoc = renderWorkspaceInstructions(spec, specRelativePath, { mirrorOf: canonicalPath });
  generatedFiles["AGENTS.md"] = nativeMirrorDoc;
  generatedFiles["AGENT.md"] = nativeMirrorDoc;
  generatedFiles["CLAUDE.md"] = nativeMirrorDoc;
  generatedFiles[".github/copilot-instructions.md"] = nativeMirrorDoc;
  generatedFiles[".github/instructions/general.instructions.md"] = `---\napplyTo: "**"\n---\n\n${nativeMirrorDoc}`;

  // --- Cursor (MDC format with frontmatter) ---
  generatedFiles[".cursor/rules/agent-instructions.mdc"] = renderCursorMdc(spec, specRelativePath);

  // --- Agents WITHOUT native skill folders (get workspace doc + inline skill summaries) ---
  const workspaceDocWithSkills = renderWorkspaceInstructions(spec, specRelativePath, { includeSkillSummaries: true, mirrorOf: canonicalPath });
  generatedFiles["GEMINI.md"] = workspaceDocWithSkills;
  generatedFiles[".amazonq/rules/general.md"] = workspaceDocWithSkills;
  generatedFiles[".junie/AGENTS.md"] = workspaceDocWithSkills;
  generatedFiles[".junie/guidelines.md"] = workspaceDocWithSkills;
  generatedFiles[".windsurf/rules/general.md"] = `---\ntrigger: always_on\n---\n\n${workspaceDocWithSkills}`;
  generatedFiles[".windsurfrules"] = workspaceDocWithSkills;
  generatedFiles[".clinerules/general.md"] = workspaceDocWithSkills;
  generatedFiles[".roo/rules/agent-instructions.md"] = workspaceDocWithSkills;
  generatedFiles[".roorules"] = workspaceDocWithSkills;
  generatedFiles[".continue/rules/agent-instructions.md"] = workspaceDocWithSkills;
  generatedFiles["CONVENTIONS.md"] = workspaceDocWithSkills;

  // --- Skills ---
  for (const skill of spec.skills ?? []) {
    const agentsSkillDir = `.agents/skills/${skill.slug}`;
    const claudeSkillDir = `.claude/skills/${skill.slug}`;
    const githubSkillDir = `.github/skills/${skill.slug}`;
    const canonicalSkillPackage = buildCanonicalSkillPackage(skill, specRelativePath);

    // Canonical, interoperable skill package
    mountSkillPackage(generatedFiles, agentsSkillDir, canonicalSkillPackage, { includeLegacyGuide: true });

    // Native mirrors projected from the canonical package
    mountSkillPackage(generatedFiles, claudeSkillDir, canonicalSkillPackage, { includeLegacyGuide: true });
    mountSkillPackage(generatedFiles, githubSkillDir, canonicalSkillPackage);

    // Cursor skill files (MDC format)
    generatedFiles[`.cursor/rules/${skill.slug}.mdc`] = renderCursorSkillMdc(skill, specRelativePath);
  }

  // --- Review Checklist ---
  if (spec.reviewChecklist) {
    generatedFiles["docs/agent-review-checklist.md"] = renderReviewChecklist(spec, specRelativePath);
  }

  // --- Manifest ---
  // The manifest must include itself in its `files` list so that every
  // rendered artifact is accounted for in a single source of truth.
  // This keeps cleanStaleFiles and checkGeneratedFiles symmetric with
  // the actual on-disk footprint and avoids a class of "needs a second
  // sync" issues where a stale path persists because no manifest layer
  // tracked it.
  const manifestPath = "docs/agent-jump-start/generated-manifest.json";
  const allPaths = [...Object.keys(generatedFiles), manifestPath].sort();
  generatedFiles[manifestPath] = `${JSON.stringify(
    {
      generatedBy: `Agent Jump Start v${TOOL_VERSION}`,
      generatedFrom: specRelativePath,
      generatorVersion: TOOL_VERSION,
      agents: [
        "Claude Code", "GitHub Copilot", "Gemini CLI", "Amazon Q Developer",
        "JetBrains Junie", "GitHub Agents", "Cursor", "Windsurf", "Cline",
        "Roo Code", "Continue.dev", "Aider",
      ],
      files: allPaths,
    },
    null,
    2,
  )}\n`;

  return generatedFiles;
}
